// Stable error codes shared between Convex mutations and the frontend, so
// catch blocks can match on a fixed code instead of an English substring
// that could drift from the thrown message.
export const ACADEMIC_YEAR_ERRORS = {
  DUPLICATE_NAME: 'ACADEMIC_YEAR_DUPLICATE_NAME',
  CANNOT_DELETE_ACTIVE: 'ACADEMIC_YEAR_CANNOT_DELETE_ACTIVE',
  INVALID_SEMESTER_COUNT: 'ACADEMIC_YEAR_INVALID_SEMESTER_COUNT',
  NOT_FOUND: 'ACADEMIC_YEAR_NOT_FOUND',
} as const

export const BRANCH_ERRORS = {
  DUPLICATE_NAME: 'BRANCH_DUPLICATE_NAME',
  NOT_FOUND: 'BRANCH_NOT_FOUND',
  IN_USE_BY_CLASS: 'BRANCH_IN_USE_BY_CLASS',
} as const

export const CLASS_ERRORS = {
  NOT_FOUND: 'CLASS_NOT_FOUND',
  IN_USE_BY_CLASS_YEAR: 'CLASS_IN_USE_BY_CLASS_YEAR',
  EMPTY_NAME: 'CLASS_EMPTY_NAME',
  CLASS_YEAR_DUPLICATE: 'CLASS_YEAR_DUPLICATE',
} as const

export const STUDENT_ERRORS = {
  NOT_FOUND: 'STUDENT_NOT_FOUND',
  IN_USE_BY_ENROLLMENT: 'STUDENT_IN_USE_BY_ENROLLMENT',
  ADDRESS_NOT_FOUND: 'STUDENT_ADDRESS_NOT_FOUND',
  EXPORT_UNAUTHORIZED: 'STUDENT_EXPORT_UNAUTHORIZED',
} as const

export const CATECHIST_ERRORS = {
  NOT_FOUND: 'CATECHIST_NOT_FOUND',
  DUPLICATE_MEMBER_ID: 'CATECHIST_DUPLICATE_MEMBER_ID',
  CONTACT_NOT_FOUND: 'CATECHIST_CONTACT_NOT_FOUND',
  ADDRESS_NOT_FOUND: 'CATECHIST_ADDRESS_NOT_FOUND',
  INVALID_PHONE: 'CATECHIST_INVALID_PHONE',
  EXPORT_UNAUTHORIZED: 'CATECHIST_EXPORT_UNAUTHORIZED',
  OWN_PROFILE_ONLY: 'CATECHIST_OWN_PROFILE_ONLY',
  OWN_ADDRESS_ONLY: 'CATECHIST_OWN_ADDRESS_ONLY',
  OWN_CONTACT_ONLY: 'CATECHIST_OWN_CONTACT_ONLY',
  OWN_PROFILE_PHOTO_UPDATE_ONLY: 'CATECHIST_OWN_PROFILE_PHOTO_UPDATE_ONLY',
  OWN_PROFILE_PHOTO_DELETE_ONLY: 'CATECHIST_OWN_PROFILE_PHOTO_DELETE_ONLY',
} as const

export const GUARDIAN_ERRORS = {
  NOT_FOUND: 'GUARDIAN_NOT_FOUND',
  CONTACT_NOT_FOUND: 'GUARDIAN_CONTACT_NOT_FOUND',
  INVALID_PHONE: 'GUARDIAN_INVALID_PHONE',
  LINK_NOT_FOUND: 'GUARDIAN_LINK_NOT_FOUND',
  DUPLICATE_LINK: 'GUARDIAN_DUPLICATE_LINK',
  DUPLICATE_PRIORITY: 'GUARDIAN_DUPLICATE_PRIORITY',
  IN_USE_BY_STUDENT: 'GUARDIAN_IN_USE_BY_STUDENT',
} as const

export const ENROLLMENT_ERRORS = {
  CLASS_YEAR_NOT_FOUND: 'ENROLLMENT_CLASS_YEAR_NOT_FOUND',
  ACADEMIC_YEAR_NOT_ACTIVE: 'ENROLLMENT_ACADEMIC_YEAR_NOT_ACTIVE',
  ALREADY_ENROLLED: 'ENROLLMENT_ALREADY_ENROLLED',
  PRIMARY_CLASS_CONFLICT: 'ENROLLMENT_PRIMARY_CLASS_CONFLICT',
  RECORD_NOT_FOUND: 'ENROLLMENT_RECORD_NOT_FOUND',
  UNAUTHORIZED: 'ENROLLMENT_UNAUTHORIZED',
  STUDENT_NOT_ENROLLED: 'ENROLLMENT_STUDENT_NOT_ENROLLED',
} as const

export const CLASS_SESSION_ERRORS = {
  NOT_FOUND: 'CLASS_SESSION_NOT_FOUND',
  INACTIVE_ACADEMIC_YEAR: 'CLASS_SESSION_INACTIVE_ACADEMIC_YEAR',
  INVALID_SCOPE: 'CLASS_SESSION_INVALID_SCOPE',
  CLASS_YEAR_NOT_FOUND: 'CLASS_SESSION_CLASS_YEAR_NOT_FOUND',
  SEMESTER_NOT_FOUND: 'CLASS_SESSION_SEMESTER_NOT_FOUND',
  NO_ACTIVE_YEAR: 'CLASS_SESSION_NO_ACTIVE_YEAR',
  ACADEMIC_YEAR_NOT_FOUND: 'CLASS_SESSION_ACADEMIC_YEAR_NOT_FOUND',
  MISSING_ACADEMIC_YEAR_REF: 'CLASS_SESSION_MISSING_ACADEMIC_YEAR_REF',
  DUPLICATE_STUDENT_IN_ATTENDANCE:
    'CLASS_SESSION_DUPLICATE_STUDENT_IN_ATTENDANCE',
  SESSION_CANCELLED: 'CLASS_SESSION_CANCELLED',
} as const

export const ATTENDANCE_ERRORS = {
  SESSION_NOT_FOUND: 'ATTENDANCE_SESSION_NOT_FOUND',
  SESSION_CANCELLED: 'ATTENDANCE_SESSION_CANCELLED',
  STUDENT_NOT_ENROLLED: 'ATTENDANCE_STUDENT_NOT_ENROLLED',
  INACTIVE_ACADEMIC_YEAR: 'ATTENDANCE_INACTIVE_ACADEMIC_YEAR',
  ALREADY_RECORDED: 'ATTENDANCE_ALREADY_RECORDED',
  RECORD_NOT_FOUND: 'ATTENDANCE_RECORD_NOT_FOUND',
} as const

export const SCORE_COLUMN_ERRORS = {
  NOT_FOUND: 'SCORE_COLUMN_NOT_FOUND',
  DUPLICATE_NAME: 'SCORE_COLUMN_DUPLICATE_NAME',
  IN_USE_BY_ENTRIES: 'SCORE_COLUMN_IN_USE_BY_ENTRIES',
  INVALID_WEIGHT: 'SCORE_COLUMN_INVALID_WEIGHT',
} as const

export const SCORE_ENTRY_ERRORS = {
  NOT_FOUND: 'SCORE_ENTRY_NOT_FOUND',
  DUPLICATE_ENTRY: 'SCORE_ENTRY_DUPLICATE_ENTRY',
  COLUMN_NOT_FOUND: 'SCORE_ENTRY_COLUMN_NOT_FOUND',
} as const

export const SEMESTER_RESULT_ERRORS = {
  NOT_FOUND: 'SEMESTER_RESULT_NOT_FOUND',
  DUPLICATE: 'SEMESTER_RESULT_DUPLICATE',
} as const

export const ANNUAL_RESULT_ERRORS = {
  NOT_FOUND: 'ANNUAL_RESULT_NOT_FOUND',
  DUPLICATE: 'ANNUAL_RESULT_DUPLICATE',
} as const

export const CALENDAR_EVENT_ERRORS = {
  NOT_FOUND: 'CALENDAR_EVENT_NOT_FOUND',
  INACTIVE_ACADEMIC_YEAR: 'CALENDAR_EVENT_INACTIVE_ACADEMIC_YEAR',
  INVALID_SCOPE: 'CALENDAR_EVENT_INVALID_SCOPE',
  BRANCH_NOT_FOUND: 'CALENDAR_EVENT_BRANCH_NOT_FOUND',
  CLASS_YEAR_NOT_FOUND: 'CALENDAR_EVENT_CLASS_YEAR_NOT_FOUND',
  UNAUTHORIZED: 'CALENDAR_EVENT_UNAUTHORIZED',
  NOT_ASSIGNED: 'CALENDAR_EVENT_NOT_ASSIGNED',
  INVALID_DATE_RANGE: 'CALENDAR_EVENT_INVALID_DATE_RANGE',
  INVALID_TIME_RANGE: 'CALENDAR_EVENT_INVALID_TIME_RANGE',
  INCOMPLETE_TIME_RANGE: 'CALENDAR_EVENT_INCOMPLETE_TIME_RANGE',
} as const

export const AUTHZ_ERRORS = {
  CATECHIST_NOT_FOUND: 'AUTHZ_CATECHIST_NOT_FOUND',
  STUDENT_NOT_FOUND: 'AUTHZ_STUDENT_NOT_FOUND',
  ACCOUNT_DELETED: 'AUTHZ_ACCOUNT_DELETED',
  ACCOUNT_INACTIVE: 'AUTHZ_ACCOUNT_INACTIVE',
  ADMIN_REQUIRED: 'AUTHZ_ADMIN_REQUIRED',
  NOT_BOARD_MEMBER: 'AUTHZ_NOT_BOARD_MEMBER',
  NOT_BRANCH_HEAD_OR_ABOVE: 'AUTHZ_NOT_BRANCH_HEAD_OR_ABOVE',
  CLASS_YEAR_NOT_FOUND: 'AUTHZ_CLASS_YEAR_NOT_FOUND',
  CLASS_NOT_FOUND: 'AUTHZ_CLASS_NOT_FOUND',
  NO_CLASS_ACCESS: 'AUTHZ_NO_CLASS_ACCESS',
  CANNOT_EDIT_STUDENT: 'AUTHZ_CANNOT_EDIT_STUDENT',
  CANNOT_MANAGE_GUARDIAN: 'AUTHZ_CANNOT_MANAGE_GUARDIAN',
  UNAUTHORIZED: 'AUTHZ_UNAUTHORIZED',
} as const

export const AUTH_ERRORS = {
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  CURRENT_PASSWORD_INCORRECT: 'AUTH_CURRENT_PASSWORD_INCORRECT',
} as const

export const SETUP_ERRORS = {
  ALREADY_COMPLETED: 'SETUP_ALREADY_COMPLETED',
  LOGIN_ID_IN_USE: 'SETUP_LOGIN_ID_IN_USE',
  PASSWORD_TOO_SHORT: 'SETUP_PASSWORD_TOO_SHORT',
} as const

export const ASSIGNMENT_ERRORS = {
  ACADEMIC_YEAR_NOT_FOUND: 'ASSIGNMENT_ACADEMIC_YEAR_NOT_FOUND',
  INACTIVE_ACADEMIC_YEAR: 'ASSIGNMENT_INACTIVE_ACADEMIC_YEAR',
  INVALID_CATECHIST: 'ASSIGNMENT_INVALID_CATECHIST',
  BRANCH_NOT_FOUND: 'ASSIGNMENT_BRANCH_NOT_FOUND',
  CLASS_YEAR_NOT_FOUND: 'ASSIGNMENT_CLASS_YEAR_NOT_FOUND',
  CLASS_YEAR_WRONG_ACADEMIC_YEAR: 'ASSIGNMENT_CLASS_YEAR_WRONG_ACADEMIC_YEAR',
  INVALID_HOMEROOM_CATECHIST: 'ASSIGNMENT_INVALID_HOMEROOM_CATECHIST',
  INVALID_CO_TEACHER_CATECHIST: 'ASSIGNMENT_INVALID_CO_TEACHER_CATECHIST',
} as const

export const GRADING_ERRORS = {
  CLASS_YEAR_NOT_FOUND: 'GRADING_CLASS_YEAR_NOT_FOUND',
  SEMESTER_NOT_FOUND: 'GRADING_SEMESTER_NOT_FOUND',
  DUPLICATE_STUDENT_IN_SCORES: 'GRADING_DUPLICATE_STUDENT_IN_SCORES',
  STUDENT_NOT_ENROLLED: 'GRADING_STUDENT_NOT_ENROLLED',
} as const

export const EXTRACURRICULAR_ERRORS = {
  NOT_FOUND: 'EXTRACURRICULAR_NOT_FOUND',
  INACTIVE_ACADEMIC_YEAR: 'EXTRACURRICULAR_INACTIVE_ACADEMIC_YEAR',
  UNAUTHORIZED: 'EXTRACURRICULAR_UNAUTHORIZED',
  INVALID_DATE_RANGE: 'EXTRACURRICULAR_INVALID_DATE_RANGE',
  INVALID_ENROLLMENT_DATE: 'EXTRACURRICULAR_INVALID_ENROLLMENT_DATE',
  ALREADY_ENROLLED: 'EXTRACURRICULAR_ALREADY_ENROLLED',
  NOT_ENROLLED: 'EXTRACURRICULAR_NOT_ENROLLED',
  CAPACITY_EXCEEDED: 'EXTRACURRICULAR_CAPACITY_EXCEEDED',
  CAPACITY_BELOW_ENROLLED: 'EXTRACURRICULAR_CAPACITY_BELOW_ENROLLED',
  PAST_START_DATE: 'EXTRACURRICULAR_PAST_START_DATE',
  BRANCH_NOT_ELIGIBLE: 'EXTRACURRICULAR_BRANCH_NOT_ELIGIBLE',
  TARGET_NOT_ELIGIBLE: 'EXTRACURRICULAR_TARGET_NOT_ELIGIBLE',
  IDENTITY_NOT_FOUND: 'EXTRACURRICULAR_IDENTITY_NOT_FOUND',
} as const

// Values below already matched the SCREAMING_SNAKE_CASE code convention as
// raw string literals in convex/accountAdmin.ts before this group existed.
// Kept identical on purpose so no test assertion changes.
export const ACCOUNT_ADMIN_ERRORS = {
  CATECHIST_NOT_FOUND: 'CATECHIST_NOT_FOUND',
  ACCOUNT_ALREADY_EXISTS: 'ACCOUNT_ALREADY_EXISTS',
  STUDENT_NOT_FOUND: 'STUDENT_NOT_FOUND',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  CANNOT_LOGIN_AS_SELF: 'CANNOT_LOGIN_AS_SELF',
  ACCOUNT_NOT_ACTIVE: 'ACCOUNT_NOT_ACTIVE',
} as const
