// Stable error codes shared between Convex mutations and the frontend, so
// catch blocks can match on a fixed code instead of an English substring
// that could drift from the thrown message.
export const ACADEMIC_YEAR_ERRORS = {
  DUPLICATE_NAME: 'ACADEMIC_YEAR_DUPLICATE_NAME',
  CANNOT_DELETE_ACTIVE: 'ACADEMIC_YEAR_CANNOT_DELETE_ACTIVE',
  INVALID_SEMESTER_COUNT: 'ACADEMIC_YEAR_INVALID_SEMESTER_COUNT',
} as const

export const BRANCH_ERRORS = {
  DUPLICATE_NAME: 'BRANCH_DUPLICATE_NAME',
  NOT_FOUND: 'BRANCH_NOT_FOUND',
  IN_USE_BY_CLASS: 'BRANCH_IN_USE_BY_CLASS',
} as const

export const CLASS_ERRORS = {
  NOT_FOUND: 'CLASS_NOT_FOUND',
  IN_USE_BY_CLASS_YEAR: 'CLASS_IN_USE_BY_CLASS_YEAR',
  EMPTY_NAME: 'CLASS_EMPTY_NAME',
  CLASS_YEAR_DUPLICATE: 'CLASS_YEAR_DUPLICATE',
} as const

export const STUDENT_ERRORS = {
  NOT_FOUND: 'STUDENT_NOT_FOUND',
  IN_USE_BY_ENROLLMENT: 'STUDENT_IN_USE_BY_ENROLLMENT',
  ADDRESS_NOT_FOUND: 'STUDENT_ADDRESS_NOT_FOUND',
} as const

export const CATECHIST_ERRORS = {
  NOT_FOUND: 'CATECHIST_NOT_FOUND',
  DUPLICATE_MEMBER_ID: 'CATECHIST_DUPLICATE_MEMBER_ID',
  CONTACT_NOT_FOUND: 'CATECHIST_CONTACT_NOT_FOUND',
  ADDRESS_NOT_FOUND: 'CATECHIST_ADDRESS_NOT_FOUND',
  INVALID_PHONE: 'CATECHIST_INVALID_PHONE',
} as const

export const GUARDIAN_ERRORS = {
  NOT_FOUND: 'GUARDIAN_NOT_FOUND',
  CONTACT_NOT_FOUND: 'GUARDIAN_CONTACT_NOT_FOUND',
  INVALID_PHONE: 'GUARDIAN_INVALID_PHONE',
  LINK_NOT_FOUND: 'GUARDIAN_LINK_NOT_FOUND',
  DUPLICATE_LINK: 'GUARDIAN_DUPLICATE_LINK',
  DUPLICATE_PRIORITY: 'GUARDIAN_DUPLICATE_PRIORITY',
  IN_USE_BY_STUDENT: 'GUARDIAN_IN_USE_BY_STUDENT',
} as const

export const ENROLLMENT_ERRORS = {
  CLASS_YEAR_NOT_FOUND: 'ENROLLMENT_CLASS_YEAR_NOT_FOUND',
  ACADEMIC_YEAR_NOT_ACTIVE: 'ENROLLMENT_ACADEMIC_YEAR_NOT_ACTIVE',
  ALREADY_ENROLLED: 'ENROLLMENT_ALREADY_ENROLLED',
  PRIMARY_CLASS_CONFLICT: 'ENROLLMENT_PRIMARY_CLASS_CONFLICT',
  RECORD_NOT_FOUND: 'ENROLLMENT_RECORD_NOT_FOUND',
  UNAUTHORIZED: 'ENROLLMENT_UNAUTHORIZED',
  STUDENT_NOT_ENROLLED: 'ENROLLMENT_STUDENT_NOT_ENROLLED',
} as const

export const CLASS_SESSION_ERRORS = {
  NOT_FOUND: 'CLASS_SESSION_NOT_FOUND',
  INACTIVE_ACADEMIC_YEAR: 'CLASS_SESSION_INACTIVE_ACADEMIC_YEAR',
  INVALID_SCOPE: 'CLASS_SESSION_INVALID_SCOPE',
  CLASS_YEAR_NOT_FOUND: 'CLASS_SESSION_CLASS_YEAR_NOT_FOUND',
  SEMESTER_NOT_FOUND: 'CLASS_SESSION_SEMESTER_NOT_FOUND',
  NO_ACTIVE_YEAR: 'CLASS_SESSION_NO_ACTIVE_YEAR',
} as const

export const ATTENDANCE_ERRORS = {
  SESSION_NOT_FOUND: 'ATTENDANCE_SESSION_NOT_FOUND',
  SESSION_CANCELLED: 'ATTENDANCE_SESSION_CANCELLED',
  STUDENT_NOT_ENROLLED: 'ATTENDANCE_STUDENT_NOT_ENROLLED',
  INACTIVE_ACADEMIC_YEAR: 'ATTENDANCE_INACTIVE_ACADEMIC_YEAR',
  ALREADY_RECORDED: 'ATTENDANCE_ALREADY_RECORDED',
  RECORD_NOT_FOUND: 'ATTENDANCE_RECORD_NOT_FOUND',
} as const

export const SCORE_COLUMN_ERRORS = {
  NOT_FOUND: 'SCORE_COLUMN_NOT_FOUND',
  DUPLICATE_NAME: 'SCORE_COLUMN_DUPLICATE_NAME',
  IN_USE_BY_ENTRIES: 'SCORE_COLUMN_IN_USE_BY_ENTRIES',
  INVALID_WEIGHT: 'SCORE_COLUMN_INVALID_WEIGHT',
} as const

export const SCORE_ENTRY_ERRORS = {
  NOT_FOUND: 'SCORE_ENTRY_NOT_FOUND',
  DUPLICATE_ENTRY: 'SCORE_ENTRY_DUPLICATE_ENTRY',
  COLUMN_NOT_FOUND: 'SCORE_ENTRY_COLUMN_NOT_FOUND',
} as const

export const SEMESTER_RESULT_ERRORS = {
  NOT_FOUND: 'SEMESTER_RESULT_NOT_FOUND',
  DUPLICATE: 'SEMESTER_RESULT_DUPLICATE',
} as const

export const ANNUAL_RESULT_ERRORS = {
  NOT_FOUND: 'ANNUAL_RESULT_NOT_FOUND',
  DUPLICATE: 'ANNUAL_RESULT_DUPLICATE',
} as const

export const CALENDAR_EVENT_ERRORS = {
  NOT_FOUND: 'CALENDAR_EVENT_NOT_FOUND',
  INACTIVE_ACADEMIC_YEAR: 'CALENDAR_EVENT_INACTIVE_ACADEMIC_YEAR',
  INVALID_SCOPE: 'CALENDAR_EVENT_INVALID_SCOPE',
  BRANCH_NOT_FOUND: 'CALENDAR_EVENT_BRANCH_NOT_FOUND',
  CLASS_YEAR_NOT_FOUND: 'CALENDAR_EVENT_CLASS_YEAR_NOT_FOUND',
  UNAUTHORIZED: 'CALENDAR_EVENT_UNAUTHORIZED',
  NOT_ASSIGNED: 'CALENDAR_EVENT_NOT_ASSIGNED',
} as const
