/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as AnotherPageRouteImport } from './routes/anotherPage'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HelpIndexRouteImport } from './routes/help.index'
import { Route as HelpRoleRouteImport } from './routes/help.$role'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/_student'
import { Route as AuthenticatedCatechistRouteImport } from './routes/_authenticated/_catechist'
import { Route as ClassesIdPhotoboothRouteImport } from './routes/classes.$id.photobooth'
import { Route as AuthenticatedStudentMyAttendanceRouteImport } from './routes/_authenticated/_student/my-attendance'
import { Route as AuthenticatedCatechistStudentsRouteImport } from './routes/_authenticated/_catechist/students'
import { Route as AuthenticatedCatechistClassesRouteImport } from './routes/_authenticated/_catechist/classes'
import { Route as AuthenticatedCatechistCatechistsRouteImport } from './routes/_authenticated/_catechist/catechists'
import { Route as AuthenticatedCatechistCalendarEventsRouteImport } from './routes/_authenticated/_catechist/calendar-events'
import { Route as AuthenticatedCatechistCalendarRouteImport } from './routes/_authenticated/_catechist/calendar'
import { Route as AuthenticatedCatechistBranchesRouteImport } from './routes/_authenticated/_catechist/branches'
import { Route as AuthenticatedCatechistAttendanceRouteImport } from './routes/_authenticated/_catechist/attendance'
import { Route as AuthenticatedCatechistAssignmentsRouteImport } from './routes/_authenticated/_catechist/assignments'
import { Route as AuthenticatedCatechistAdminRouteImport } from './routes/_authenticated/_catechist/_admin'
import { Route as AuthenticatedCatechistStudentsPromoteRouteImport } from './routes/_authenticated/_catechist/students_.promote'
import { Route as AuthenticatedCatechistStudentsCreateRouteImport } from './routes/_authenticated/_catechist/students_.create'
import { Route as AuthenticatedCatechistStudentsIdRouteImport } from './routes/_authenticated/_catechist/students_.$id'
import { Route as AuthenticatedCatechistReportsMassExtraAttendanceRouteImport } from './routes/_authenticated/_catechist/reports_.mass-extra-attendance'
import { Route as AuthenticatedCatechistReportsAcademicYearsComparisonRouteImport } from './routes/_authenticated/_catechist/reports_.academic-years-comparison'
import { Route as AuthenticatedCatechistReportsAcademicYearReportRouteImport } from './routes/_authenticated/_catechist/reports_.academic-year-report'
import { Route as AuthenticatedCatechistClassesCreateRouteImport } from './routes/_authenticated/_catechist/classes_.create'
import { Route as AuthenticatedCatechistClassesBulkCreateRouteImport } from './routes/_authenticated/_catechist/classes_.bulk-create'
import { Route as AuthenticatedCatechistClassesIdRouteImport } from './routes/_authenticated/_catechist/classes_.$id'
import { Route as AuthenticatedCatechistCatechistsCreateRouteImport } from './routes/_authenticated/_catechist/catechists_.create'
import { Route as AuthenticatedCatechistCatechistsIdRouteImport } from './routes/_authenticated/_catechist/catechists_.$id'
import { Route as AuthenticatedCatechistBranchesCreateRouteImport } from './routes/_authenticated/_catechist/branches_.create'
import { Route as AuthenticatedCatechistBranchesIdRouteImport } from './routes/_authenticated/_catechist/branches_.$id'
import { Route as AuthenticatedCatechistAssignmentsEditRouteImport } from './routes/_authenticated/_catechist/assignments_.edit'
import { Route as AuthenticatedCatechistAdminStudentAccountsRouteImport } from './routes/_authenticated/_catechist/_admin/student-accounts'
import { Route as AuthenticatedCatechistAdminImportRouteImport } from './routes/_authenticated/_catechist/_admin/import'
import { Route as AuthenticatedCatechistAdminCatechistAccountsRouteImport } from './routes/_authenticated/_catechist/_admin/catechist-accounts'
import { Route as AuthenticatedCatechistAdminAppConfigRouteImport } from './routes/_authenticated/_catechist/_admin/app-config'
import { Route as AuthenticatedCatechistAdminAcademicYearsRouteImport } from './routes/_authenticated/_catechist/_admin/academic-years'
import { Route as AuthenticatedCatechistStudentsIdEditRouteImport } from './routes/_authenticated/_catechist/students_.$id_.edit'
import { Route as AuthenticatedCatechistStudentsIdAttendanceRouteImport } from './routes/_authenticated/_catechist/students_.$id_.attendance'
import { Route as AuthenticatedCatechistClassesIdEditRouteImport } from './routes/_authenticated/_catechist/classes_.$id_.edit'
import { Route as AuthenticatedCatechistCatechistsIdEditRouteImport } from './routes/_authenticated/_catechist/catechists_.$id_.edit'
import { Route as AuthenticatedCatechistBranchesIdEditRouteImport } from './routes/_authenticated/_catechist/branches_.$id_.edit'
import { Route as AuthenticatedCatechistAdminAcademicYearsSetupRouteImport } from './routes/_authenticated/_catechist/_admin/academic-years_.setup'
import { Route as AuthenticatedCatechistAdminAcademicYearsCreateRouteImport } from './routes/_authenticated/_catechist/_admin/academic-years_.create'
import { Route as AuthenticatedCatechistAdminAcademicYearsIdRouteImport } from './routes/_authenticated/_catechist/_admin/academic-years_.$id'
import { Route as AuthenticatedCatechistClassesIdSessionsCreateRouteImport } from './routes/_authenticated/_catechist/classes_.$id_.sessions_.create'
import { Route as AuthenticatedCatechistClassesIdExamsCreateRouteImport } from './routes/_authenticated/_catechist/classes_.$id_.exams_.create'
import { Route as AuthenticatedCatechistAdminAcademicYearsIdEditRouteImport } from './routes/_authenticated/_catechist/_admin/academic-years_.$id_.edit'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AnotherPageRoute = AnotherPageRouteImport.update({
  id: '/anotherPage',
  path: '/anotherPage',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HelpRoute,
} as any)
const HelpRoleRoute = HelpRoleRouteImport.update({
  id: '/$role',
  path: '/$role',
  getParentRoute: () => HelpRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCatechistRoute = AuthenticatedCatechistRouteImport.update({
  id: '/_catechist',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ClassesIdPhotoboothRoute = ClassesIdPhotoboothRouteImport.update({
  id: '/classes/$id/photobooth',
  path: '/classes/$id/photobooth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentMyAttendanceRoute =
  AuthenticatedStudentMyAttendanceRouteImport.update({
    id: '/my-attendance',
    path: '/my-attendance',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedCatechistStudentsRoute =
  AuthenticatedCatechistStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistClassesRoute =
  AuthenticatedCatechistClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistCatechistsRoute =
  AuthenticatedCatechistCatechistsRouteImport.update({
    id: '/catechists',
    path: '/catechists',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistCalendarEventsRoute =
  AuthenticatedCatechistCalendarEventsRouteImport.update({
    id: '/calendar-events',
    path: '/calendar-events',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistCalendarRoute =
  AuthenticatedCatechistCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistBranchesRoute =
  AuthenticatedCatechistBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistAttendanceRoute =
  AuthenticatedCatechistAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistAssignmentsRoute =
  AuthenticatedCatechistAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistAdminRoute =
  AuthenticatedCatechistAdminRouteImport.update({
    id: '/_admin',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistStudentsPromoteRoute =
  AuthenticatedCatechistStudentsPromoteRouteImport.update({
    id: '/students_/promote',
    path: '/students/promote',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistStudentsCreateRoute =
  AuthenticatedCatechistStudentsCreateRouteImport.update({
    id: '/students_/create',
    path: '/students/create',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistStudentsIdRoute =
  AuthenticatedCatechistStudentsIdRouteImport.update({
    id: '/students_/$id',
    path: '/students/$id',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistReportsMassExtraAttendanceRoute =
  AuthenticatedCatechistReportsMassExtraAttendanceRouteImport.update({
    id: '/reports_/mass-extra-attendance',
    path: '/reports/mass-extra-attendance',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistReportsAcademicYearsComparisonRoute =
  AuthenticatedCatechistReportsAcademicYearsComparisonRouteImport.update({
    id: '/reports_/academic-years-comparison',
    path: '/reports/academic-years-comparison',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistReportsAcademicYearReportRoute =
  AuthenticatedCatechistReportsAcademicYearReportRouteImport.update({
    id: '/reports_/academic-year-report',
    path: '/reports/academic-year-report',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistClassesCreateRoute =
  AuthenticatedCatechistClassesCreateRouteImport.update({
    id: '/classes_/create',
    path: '/classes/create',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistClassesBulkCreateRoute =
  AuthenticatedCatechistClassesBulkCreateRouteImport.update({
    id: '/classes_/bulk-create',
    path: '/classes/bulk-create',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistClassesIdRoute =
  AuthenticatedCatechistClassesIdRouteImport.update({
    id: '/classes_/$id',
    path: '/classes/$id',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistCatechistsCreateRoute =
  AuthenticatedCatechistCatechistsCreateRouteImport.update({
    id: '/catechists_/create',
    path: '/catechists/create',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistCatechistsIdRoute =
  AuthenticatedCatechistCatechistsIdRouteImport.update({
    id: '/catechists_/$id',
    path: '/catechists/$id',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistBranchesCreateRoute =
  AuthenticatedCatechistBranchesCreateRouteImport.update({
    id: '/branches_/create',
    path: '/branches/create',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistBranchesIdRoute =
  AuthenticatedCatechistBranchesIdRouteImport.update({
    id: '/branches_/$id',
    path: '/branches/$id',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistAssignmentsEditRoute =
  AuthenticatedCatechistAssignmentsEditRouteImport.update({
    id: '/assignments_/edit',
    path: '/assignments/edit',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistAdminStudentAccountsRoute =
  AuthenticatedCatechistAdminStudentAccountsRouteImport.update({
    id: '/student-accounts',
    path: '/student-accounts',
    getParentRoute: () => AuthenticatedCatechistAdminRoute,
  } as any)
const AuthenticatedCatechistAdminImportRoute =
  AuthenticatedCatechistAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedCatechistAdminRoute,
  } as any)
const AuthenticatedCatechistAdminCatechistAccountsRoute =
  AuthenticatedCatechistAdminCatechistAccountsRouteImport.update({
    id: '/catechist-accounts',
    path: '/catechist-accounts',
    getParentRoute: () => AuthenticatedCatechistAdminRoute,
  } as any)
const AuthenticatedCatechistAdminAppConfigRoute =
  AuthenticatedCatechistAdminAppConfigRouteImport.update({
    id: '/app-config',
    path: '/app-config',
    getParentRoute: () => AuthenticatedCatechistAdminRoute,
  } as any)
const AuthenticatedCatechistAdminAcademicYearsRoute =
  AuthenticatedCatechistAdminAcademicYearsRouteImport.update({
    id: '/academic-years',
    path: '/academic-years',
    getParentRoute: () => AuthenticatedCatechistAdminRoute,
  } as any)
const AuthenticatedCatechistStudentsIdEditRoute =
  AuthenticatedCatechistStudentsIdEditRouteImport.update({
    id: '/students_/$id_/edit',
    path: '/students/$id/edit',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistStudentsIdAttendanceRoute =
  AuthenticatedCatechistStudentsIdAttendanceRouteImport.update({
    id: '/students_/$id_/attendance',
    path: '/students/$id/attendance',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistClassesIdEditRoute =
  AuthenticatedCatechistClassesIdEditRouteImport.update({
    id: '/classes_/$id_/edit',
    path: '/classes/$id/edit',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistCatechistsIdEditRoute =
  AuthenticatedCatechistCatechistsIdEditRouteImport.update({
    id: '/catechists_/$id_/edit',
    path: '/catechists/$id/edit',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistBranchesIdEditRoute =
  AuthenticatedCatechistBranchesIdEditRouteImport.update({
    id: '/branches_/$id_/edit',
    path: '/branches/$id/edit',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistAdminAcademicYearsSetupRoute =
  AuthenticatedCatechistAdminAcademicYearsSetupRouteImport.update({
    id: '/academic-years_/setup',
    path: '/academic-years/setup',
    getParentRoute: () => AuthenticatedCatechistAdminRoute,
  } as any)
const AuthenticatedCatechistAdminAcademicYearsCreateRoute =
  AuthenticatedCatechistAdminAcademicYearsCreateRouteImport.update({
    id: '/academic-years_/create',
    path: '/academic-years/create',
    getParentRoute: () => AuthenticatedCatechistAdminRoute,
  } as any)
const AuthenticatedCatechistAdminAcademicYearsIdRoute =
  AuthenticatedCatechistAdminAcademicYearsIdRouteImport.update({
    id: '/academic-years_/$id',
    path: '/academic-years/$id',
    getParentRoute: () => AuthenticatedCatechistAdminRoute,
  } as any)
const AuthenticatedCatechistClassesIdSessionsCreateRoute =
  AuthenticatedCatechistClassesIdSessionsCreateRouteImport.update({
    id: '/classes_/$id_/sessions_/create',
    path: '/classes/$id/sessions/create',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistClassesIdExamsCreateRoute =
  AuthenticatedCatechistClassesIdExamsCreateRouteImport.update({
    id: '/classes_/$id_/exams_/create',
    path: '/classes/$id/exams/create',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistAdminAcademicYearsIdEditRoute =
  AuthenticatedCatechistAdminAcademicYearsIdEditRouteImport.update({
    id: '/academic-years_/$id_/edit',
    path: '/academic-years/$id/edit',
    getParentRoute: () => AuthenticatedCatechistAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anotherPage': typeof AnotherPageRoute
  '/help': typeof HelpRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/help/$role': typeof HelpRoleRoute
  '/help/': typeof HelpIndexRoute
  '/assignments': typeof AuthenticatedCatechistAssignmentsRoute
  '/attendance': typeof AuthenticatedCatechistAttendanceRoute
  '/branches': typeof AuthenticatedCatechistBranchesRoute
  '/calendar': typeof AuthenticatedCatechistCalendarRoute
  '/calendar-events': typeof AuthenticatedCatechistCalendarEventsRoute
  '/catechists': typeof AuthenticatedCatechistCatechistsRoute
  '/classes': typeof AuthenticatedCatechistClassesRoute
  '/students': typeof AuthenticatedCatechistStudentsRoute
  '/my-attendance': typeof AuthenticatedStudentMyAttendanceRoute
  '/classes/$id/photobooth': typeof ClassesIdPhotoboothRoute
  '/academic-years': typeof AuthenticatedCatechistAdminAcademicYearsRoute
  '/app-config': typeof AuthenticatedCatechistAdminAppConfigRoute
  '/catechist-accounts': typeof AuthenticatedCatechistAdminCatechistAccountsRoute
  '/import': typeof AuthenticatedCatechistAdminImportRoute
  '/student-accounts': typeof AuthenticatedCatechistAdminStudentAccountsRoute
  '/assignments/edit': typeof AuthenticatedCatechistAssignmentsEditRoute
  '/branches/$id': typeof AuthenticatedCatechistBranchesIdRoute
  '/branches/create': typeof AuthenticatedCatechistBranchesCreateRoute
  '/catechists/$id': typeof AuthenticatedCatechistCatechistsIdRoute
  '/catechists/create': typeof AuthenticatedCatechistCatechistsCreateRoute
  '/classes/$id': typeof AuthenticatedCatechistClassesIdRoute
  '/classes/bulk-create': typeof AuthenticatedCatechistClassesBulkCreateRoute
  '/classes/create': typeof AuthenticatedCatechistClassesCreateRoute
  '/reports/academic-year-report': typeof AuthenticatedCatechistReportsAcademicYearReportRoute
  '/reports/academic-years-comparison': typeof AuthenticatedCatechistReportsAcademicYearsComparisonRoute
  '/reports/mass-extra-attendance': typeof AuthenticatedCatechistReportsMassExtraAttendanceRoute
  '/students/$id': typeof AuthenticatedCatechistStudentsIdRoute
  '/students/create': typeof AuthenticatedCatechistStudentsCreateRoute
  '/students/promote': typeof AuthenticatedCatechistStudentsPromoteRoute
  '/academic-years/$id': typeof AuthenticatedCatechistAdminAcademicYearsIdRoute
  '/academic-years/create': typeof AuthenticatedCatechistAdminAcademicYearsCreateRoute
  '/academic-years/setup': typeof AuthenticatedCatechistAdminAcademicYearsSetupRoute
  '/branches/$id/edit': typeof AuthenticatedCatechistBranchesIdEditRoute
  '/catechists/$id/edit': typeof AuthenticatedCatechistCatechistsIdEditRoute
  '/classes/$id/edit': typeof AuthenticatedCatechistClassesIdEditRoute
  '/students/$id/attendance': typeof AuthenticatedCatechistStudentsIdAttendanceRoute
  '/students/$id/edit': typeof AuthenticatedCatechistStudentsIdEditRoute
  '/academic-years/$id/edit': typeof AuthenticatedCatechistAdminAcademicYearsIdEditRoute
  '/classes/$id/exams/create': typeof AuthenticatedCatechistClassesIdExamsCreateRoute
  '/classes/$id/sessions/create': typeof AuthenticatedCatechistClassesIdSessionsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anotherPage': typeof AnotherPageRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/help/$role': typeof HelpRoleRoute
  '/help': typeof HelpIndexRoute
  '/assignments': typeof AuthenticatedCatechistAssignmentsRoute
  '/attendance': typeof AuthenticatedCatechistAttendanceRoute
  '/branches': typeof AuthenticatedCatechistBranchesRoute
  '/calendar': typeof AuthenticatedCatechistCalendarRoute
  '/calendar-events': typeof AuthenticatedCatechistCalendarEventsRoute
  '/catechists': typeof AuthenticatedCatechistCatechistsRoute
  '/classes': typeof AuthenticatedCatechistClassesRoute
  '/students': typeof AuthenticatedCatechistStudentsRoute
  '/my-attendance': typeof AuthenticatedStudentMyAttendanceRoute
  '/classes/$id/photobooth': typeof ClassesIdPhotoboothRoute
  '/academic-years': typeof AuthenticatedCatechistAdminAcademicYearsRoute
  '/app-config': typeof AuthenticatedCatechistAdminAppConfigRoute
  '/catechist-accounts': typeof AuthenticatedCatechistAdminCatechistAccountsRoute
  '/import': typeof AuthenticatedCatechistAdminImportRoute
  '/student-accounts': typeof AuthenticatedCatechistAdminStudentAccountsRoute
  '/assignments/edit': typeof AuthenticatedCatechistAssignmentsEditRoute
  '/branches/$id': typeof AuthenticatedCatechistBranchesIdRoute
  '/branches/create': typeof AuthenticatedCatechistBranchesCreateRoute
  '/catechists/$id': typeof AuthenticatedCatechistCatechistsIdRoute
  '/catechists/create': typeof AuthenticatedCatechistCatechistsCreateRoute
  '/classes/$id': typeof AuthenticatedCatechistClassesIdRoute
  '/classes/bulk-create': typeof AuthenticatedCatechistClassesBulkCreateRoute
  '/classes/create': typeof AuthenticatedCatechistClassesCreateRoute
  '/reports/academic-year-report': typeof AuthenticatedCatechistReportsAcademicYearReportRoute
  '/reports/academic-years-comparison': typeof AuthenticatedCatechistReportsAcademicYearsComparisonRoute
  '/reports/mass-extra-attendance': typeof AuthenticatedCatechistReportsMassExtraAttendanceRoute
  '/students/$id': typeof AuthenticatedCatechistStudentsIdRoute
  '/students/create': typeof AuthenticatedCatechistStudentsCreateRoute
  '/students/promote': typeof AuthenticatedCatechistStudentsPromoteRoute
  '/academic-years/$id': typeof AuthenticatedCatechistAdminAcademicYearsIdRoute
  '/academic-years/create': typeof AuthenticatedCatechistAdminAcademicYearsCreateRoute
  '/academic-years/setup': typeof AuthenticatedCatechistAdminAcademicYearsSetupRoute
  '/branches/$id/edit': typeof AuthenticatedCatechistBranchesIdEditRoute
  '/catechists/$id/edit': typeof AuthenticatedCatechistCatechistsIdEditRoute
  '/classes/$id/edit': typeof AuthenticatedCatechistClassesIdEditRoute
  '/students/$id/attendance': typeof AuthenticatedCatechistStudentsIdAttendanceRoute
  '/students/$id/edit': typeof AuthenticatedCatechistStudentsIdEditRoute
  '/academic-years/$id/edit': typeof AuthenticatedCatechistAdminAcademicYearsIdEditRoute
  '/classes/$id/exams/create': typeof AuthenticatedCatechistClassesIdExamsCreateRoute
  '/classes/$id/sessions/create': typeof AuthenticatedCatechistClassesIdSessionsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/anotherPage': typeof AnotherPageRoute
  '/help': typeof HelpRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_authenticated/_catechist': typeof AuthenticatedCatechistRouteWithChildren
  '/_authenticated/_student': typeof AuthenticatedStudentRouteWithChildren
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/help/$role': typeof HelpRoleRoute
  '/help/': typeof HelpIndexRoute
  '/_authenticated/_catechist/_admin': typeof AuthenticatedCatechistAdminRouteWithChildren
  '/_authenticated/_catechist/assignments': typeof AuthenticatedCatechistAssignmentsRoute
  '/_authenticated/_catechist/attendance': typeof AuthenticatedCatechistAttendanceRoute
  '/_authenticated/_catechist/branches': typeof AuthenticatedCatechistBranchesRoute
  '/_authenticated/_catechist/calendar': typeof AuthenticatedCatechistCalendarRoute
  '/_authenticated/_catechist/calendar-events': typeof AuthenticatedCatechistCalendarEventsRoute
  '/_authenticated/_catechist/catechists': typeof AuthenticatedCatechistCatechistsRoute
  '/_authenticated/_catechist/classes': typeof AuthenticatedCatechistClassesRoute
  '/_authenticated/_catechist/students': typeof AuthenticatedCatechistStudentsRoute
  '/_authenticated/_student/my-attendance': typeof AuthenticatedStudentMyAttendanceRoute
  '/classes/$id/photobooth': typeof ClassesIdPhotoboothRoute
  '/_authenticated/_catechist/_admin/academic-years': typeof AuthenticatedCatechistAdminAcademicYearsRoute
  '/_authenticated/_catechist/_admin/app-config': typeof AuthenticatedCatechistAdminAppConfigRoute
  '/_authenticated/_catechist/_admin/catechist-accounts': typeof AuthenticatedCatechistAdminCatechistAccountsRoute
  '/_authenticated/_catechist/_admin/import': typeof AuthenticatedCatechistAdminImportRoute
  '/_authenticated/_catechist/_admin/student-accounts': typeof AuthenticatedCatechistAdminStudentAccountsRoute
  '/_authenticated/_catechist/assignments_/edit': typeof AuthenticatedCatechistAssignmentsEditRoute
  '/_authenticated/_catechist/branches_/$id': typeof AuthenticatedCatechistBranchesIdRoute
  '/_authenticated/_catechist/branches_/create': typeof AuthenticatedCatechistBranchesCreateRoute
  '/_authenticated/_catechist/catechists_/$id': typeof AuthenticatedCatechistCatechistsIdRoute
  '/_authenticated/_catechist/catechists_/create': typeof AuthenticatedCatechistCatechistsCreateRoute
  '/_authenticated/_catechist/classes_/$id': typeof AuthenticatedCatechistClassesIdRoute
  '/_authenticated/_catechist/classes_/bulk-create': typeof AuthenticatedCatechistClassesBulkCreateRoute
  '/_authenticated/_catechist/classes_/create': typeof AuthenticatedCatechistClassesCreateRoute
  '/_authenticated/_catechist/reports_/academic-year-report': typeof AuthenticatedCatechistReportsAcademicYearReportRoute
  '/_authenticated/_catechist/reports_/academic-years-comparison': typeof AuthenticatedCatechistReportsAcademicYearsComparisonRoute
  '/_authenticated/_catechist/reports_/mass-extra-attendance': typeof AuthenticatedCatechistReportsMassExtraAttendanceRoute
  '/_authenticated/_catechist/students_/$id': typeof AuthenticatedCatechistStudentsIdRoute
  '/_authenticated/_catechist/students_/create': typeof AuthenticatedCatechistStudentsCreateRoute
  '/_authenticated/_catechist/students_/promote': typeof AuthenticatedCatechistStudentsPromoteRoute
  '/_authenticated/_catechist/_admin/academic-years_/$id': typeof AuthenticatedCatechistAdminAcademicYearsIdRoute
  '/_authenticated/_catechist/_admin/academic-years_/create': typeof AuthenticatedCatechistAdminAcademicYearsCreateRoute
  '/_authenticated/_catechist/_admin/academic-years_/setup': typeof AuthenticatedCatechistAdminAcademicYearsSetupRoute
  '/_authenticated/_catechist/branches_/$id_/edit': typeof AuthenticatedCatechistBranchesIdEditRoute
  '/_authenticated/_catechist/catechists_/$id_/edit': typeof AuthenticatedCatechistCatechistsIdEditRoute
  '/_authenticated/_catechist/classes_/$id_/edit': typeof AuthenticatedCatechistClassesIdEditRoute
  '/_authenticated/_catechist/students_/$id_/attendance': typeof AuthenticatedCatechistStudentsIdAttendanceRoute
  '/_authenticated/_catechist/students_/$id_/edit': typeof AuthenticatedCatechistStudentsIdEditRoute
  '/_authenticated/_catechist/_admin/academic-years_/$id_/edit': typeof AuthenticatedCatechistAdminAcademicYearsIdEditRoute
  '/_authenticated/_catechist/classes_/$id_/exams_/create': typeof AuthenticatedCatechistClassesIdExamsCreateRoute
  '/_authenticated/_catechist/classes_/$id_/sessions_/create': typeof AuthenticatedCatechistClassesIdSessionsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anotherPage'
    | '/help'
    | '/login'
    | '/setup'
    | '/change-password'
    | '/dashboard'
    | '/profile'
    | '/help/$role'
    | '/help/'
    | '/assignments'
    | '/attendance'
    | '/branches'
    | '/calendar'
    | '/calendar-events'
    | '/catechists'
    | '/classes'
    | '/students'
    | '/my-attendance'
    | '/classes/$id/photobooth'
    | '/academic-years'
    | '/app-config'
    | '/catechist-accounts'
    | '/import'
    | '/student-accounts'
    | '/assignments/edit'
    | '/branches/$id'
    | '/branches/create'
    | '/catechists/$id'
    | '/catechists/create'
    | '/classes/$id'
    | '/classes/bulk-create'
    | '/classes/create'
    | '/reports/academic-year-report'
    | '/reports/academic-years-comparison'
    | '/reports/mass-extra-attendance'
    | '/students/$id'
    | '/students/create'
    | '/students/promote'
    | '/academic-years/$id'
    | '/academic-years/create'
    | '/academic-years/setup'
    | '/branches/$id/edit'
    | '/catechists/$id/edit'
    | '/classes/$id/edit'
    | '/students/$id/attendance'
    | '/students/$id/edit'
    | '/academic-years/$id/edit'
    | '/classes/$id/exams/create'
    | '/classes/$id/sessions/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anotherPage'
    | '/login'
    | '/setup'
    | '/change-password'
    | '/dashboard'
    | '/profile'
    | '/help/$role'
    | '/help'
    | '/assignments'
    | '/attendance'
    | '/branches'
    | '/calendar'
    | '/calendar-events'
    | '/catechists'
    | '/classes'
    | '/students'
    | '/my-attendance'
    | '/classes/$id/photobooth'
    | '/academic-years'
    | '/app-config'
    | '/catechist-accounts'
    | '/import'
    | '/student-accounts'
    | '/assignments/edit'
    | '/branches/$id'
    | '/branches/create'
    | '/catechists/$id'
    | '/catechists/create'
    | '/classes/$id'
    | '/classes/bulk-create'
    | '/classes/create'
    | '/reports/academic-year-report'
    | '/reports/academic-years-comparison'
    | '/reports/mass-extra-attendance'
    | '/students/$id'
    | '/students/create'
    | '/students/promote'
    | '/academic-years/$id'
    | '/academic-years/create'
    | '/academic-years/setup'
    | '/branches/$id/edit'
    | '/catechists/$id/edit'
    | '/classes/$id/edit'
    | '/students/$id/attendance'
    | '/students/$id/edit'
    | '/academic-years/$id/edit'
    | '/classes/$id/exams/create'
    | '/classes/$id/sessions/create'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/anotherPage'
    | '/help'
    | '/login'
    | '/setup'
    | '/_authenticated/_catechist'
    | '/_authenticated/_student'
    | '/_authenticated/change-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/help/$role'
    | '/help/'
    | '/_authenticated/_catechist/_admin'
    | '/_authenticated/_catechist/assignments'
    | '/_authenticated/_catechist/attendance'
    | '/_authenticated/_catechist/branches'
    | '/_authenticated/_catechist/calendar'
    | '/_authenticated/_catechist/calendar-events'
    | '/_authenticated/_catechist/catechists'
    | '/_authenticated/_catechist/classes'
    | '/_authenticated/_catechist/students'
    | '/_authenticated/_student/my-attendance'
    | '/classes/$id/photobooth'
    | '/_authenticated/_catechist/_admin/academic-years'
    | '/_authenticated/_catechist/_admin/app-config'
    | '/_authenticated/_catechist/_admin/catechist-accounts'
    | '/_authenticated/_catechist/_admin/import'
    | '/_authenticated/_catechist/_admin/student-accounts'
    | '/_authenticated/_catechist/assignments_/edit'
    | '/_authenticated/_catechist/branches_/$id'
    | '/_authenticated/_catechist/branches_/create'
    | '/_authenticated/_catechist/catechists_/$id'
    | '/_authenticated/_catechist/catechists_/create'
    | '/_authenticated/_catechist/classes_/$id'
    | '/_authenticated/_catechist/classes_/bulk-create'
    | '/_authenticated/_catechist/classes_/create'
    | '/_authenticated/_catechist/reports_/academic-year-report'
    | '/_authenticated/_catechist/reports_/academic-years-comparison'
    | '/_authenticated/_catechist/reports_/mass-extra-attendance'
    | '/_authenticated/_catechist/students_/$id'
    | '/_authenticated/_catechist/students_/create'
    | '/_authenticated/_catechist/students_/promote'
    | '/_authenticated/_catechist/_admin/academic-years_/$id'
    | '/_authenticated/_catechist/_admin/academic-years_/create'
    | '/_authenticated/_catechist/_admin/academic-years_/setup'
    | '/_authenticated/_catechist/branches_/$id_/edit'
    | '/_authenticated/_catechist/catechists_/$id_/edit'
    | '/_authenticated/_catechist/classes_/$id_/edit'
    | '/_authenticated/_catechist/students_/$id_/attendance'
    | '/_authenticated/_catechist/students_/$id_/edit'
    | '/_authenticated/_catechist/_admin/academic-years_/$id_/edit'
    | '/_authenticated/_catechist/classes_/$id_/exams_/create'
    | '/_authenticated/_catechist/classes_/$id_/sessions_/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AnotherPageRoute: typeof AnotherPageRoute
  HelpRoute: typeof HelpRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  ClassesIdPhotoboothRoute: typeof ClassesIdPhotoboothRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anotherPage': {
      id: '/anotherPage'
      path: '/anotherPage'
      fullPath: '/anotherPage'
      preLoaderRoute: typeof AnotherPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/$role': {
      id: '/help/$role'
      path: '/$role'
      fullPath: '/help/$role'
      preLoaderRoute: typeof HelpRoleRouteImport
      parentRoute: typeof HelpRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_student': {
      id: '/_authenticated/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_catechist': {
      id: '/_authenticated/_catechist'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedCatechistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/classes/$id/photobooth': {
      id: '/classes/$id/photobooth'
      path: '/classes/$id/photobooth'
      fullPath: '/classes/$id/photobooth'
      preLoaderRoute: typeof ClassesIdPhotoboothRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_student/my-attendance': {
      id: '/_authenticated/_student/my-attendance'
      path: '/my-attendance'
      fullPath: '/my-attendance'
      preLoaderRoute: typeof AuthenticatedStudentMyAttendanceRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/_catechist/students': {
      id: '/_authenticated/_catechist/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedCatechistStudentsRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/classes': {
      id: '/_authenticated/_catechist/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedCatechistClassesRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/catechists': {
      id: '/_authenticated/_catechist/catechists'
      path: '/catechists'
      fullPath: '/catechists'
      preLoaderRoute: typeof AuthenticatedCatechistCatechistsRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/calendar-events': {
      id: '/_authenticated/_catechist/calendar-events'
      path: '/calendar-events'
      fullPath: '/calendar-events'
      preLoaderRoute: typeof AuthenticatedCatechistCalendarEventsRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/calendar': {
      id: '/_authenticated/_catechist/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCatechistCalendarRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/branches': {
      id: '/_authenticated/_catechist/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedCatechistBranchesRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/attendance': {
      id: '/_authenticated/_catechist/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedCatechistAttendanceRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/assignments': {
      id: '/_authenticated/_catechist/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedCatechistAssignmentsRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/_admin': {
      id: '/_authenticated/_catechist/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedCatechistAdminRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/students_/promote': {
      id: '/_authenticated/_catechist/students_/promote'
      path: '/students/promote'
      fullPath: '/students/promote'
      preLoaderRoute: typeof AuthenticatedCatechistStudentsPromoteRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/students_/create': {
      id: '/_authenticated/_catechist/students_/create'
      path: '/students/create'
      fullPath: '/students/create'
      preLoaderRoute: typeof AuthenticatedCatechistStudentsCreateRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/students_/$id': {
      id: '/_authenticated/_catechist/students_/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AuthenticatedCatechistStudentsIdRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/reports_/mass-extra-attendance': {
      id: '/_authenticated/_catechist/reports_/mass-extra-attendance'
      path: '/reports/mass-extra-attendance'
      fullPath: '/reports/mass-extra-attendance'
      preLoaderRoute: typeof AuthenticatedCatechistReportsMassExtraAttendanceRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/reports_/academic-years-comparison': {
      id: '/_authenticated/_catechist/reports_/academic-years-comparison'
      path: '/reports/academic-years-comparison'
      fullPath: '/reports/academic-years-comparison'
      preLoaderRoute: typeof AuthenticatedCatechistReportsAcademicYearsComparisonRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/reports_/academic-year-report': {
      id: '/_authenticated/_catechist/reports_/academic-year-report'
      path: '/reports/academic-year-report'
      fullPath: '/reports/academic-year-report'
      preLoaderRoute: typeof AuthenticatedCatechistReportsAcademicYearReportRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/classes_/create': {
      id: '/_authenticated/_catechist/classes_/create'
      path: '/classes/create'
      fullPath: '/classes/create'
      preLoaderRoute: typeof AuthenticatedCatechistClassesCreateRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/classes_/bulk-create': {
      id: '/_authenticated/_catechist/classes_/bulk-create'
      path: '/classes/bulk-create'
      fullPath: '/classes/bulk-create'
      preLoaderRoute: typeof AuthenticatedCatechistClassesBulkCreateRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/classes_/$id': {
      id: '/_authenticated/_catechist/classes_/$id'
      path: '/classes/$id'
      fullPath: '/classes/$id'
      preLoaderRoute: typeof AuthenticatedCatechistClassesIdRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/catechists_/create': {
      id: '/_authenticated/_catechist/catechists_/create'
      path: '/catechists/create'
      fullPath: '/catechists/create'
      preLoaderRoute: typeof AuthenticatedCatechistCatechistsCreateRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/catechists_/$id': {
      id: '/_authenticated/_catechist/catechists_/$id'
      path: '/catechists/$id'
      fullPath: '/catechists/$id'
      preLoaderRoute: typeof AuthenticatedCatechistCatechistsIdRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/branches_/create': {
      id: '/_authenticated/_catechist/branches_/create'
      path: '/branches/create'
      fullPath: '/branches/create'
      preLoaderRoute: typeof AuthenticatedCatechistBranchesCreateRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/branches_/$id': {
      id: '/_authenticated/_catechist/branches_/$id'
      path: '/branches/$id'
      fullPath: '/branches/$id'
      preLoaderRoute: typeof AuthenticatedCatechistBranchesIdRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/assignments_/edit': {
      id: '/_authenticated/_catechist/assignments_/edit'
      path: '/assignments/edit'
      fullPath: '/assignments/edit'
      preLoaderRoute: typeof AuthenticatedCatechistAssignmentsEditRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/_admin/student-accounts': {
      id: '/_authenticated/_catechist/_admin/student-accounts'
      path: '/student-accounts'
      fullPath: '/student-accounts'
      preLoaderRoute: typeof AuthenticatedCatechistAdminStudentAccountsRouteImport
      parentRoute: typeof AuthenticatedCatechistAdminRoute
    }
    '/_authenticated/_catechist/_admin/import': {
      id: '/_authenticated/_catechist/_admin/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedCatechistAdminImportRouteImport
      parentRoute: typeof AuthenticatedCatechistAdminRoute
    }
    '/_authenticated/_catechist/_admin/catechist-accounts': {
      id: '/_authenticated/_catechist/_admin/catechist-accounts'
      path: '/catechist-accounts'
      fullPath: '/catechist-accounts'
      preLoaderRoute: typeof AuthenticatedCatechistAdminCatechistAccountsRouteImport
      parentRoute: typeof AuthenticatedCatechistAdminRoute
    }
    '/_authenticated/_catechist/_admin/app-config': {
      id: '/_authenticated/_catechist/_admin/app-config'
      path: '/app-config'
      fullPath: '/app-config'
      preLoaderRoute: typeof AuthenticatedCatechistAdminAppConfigRouteImport
      parentRoute: typeof AuthenticatedCatechistAdminRoute
    }
    '/_authenticated/_catechist/_admin/academic-years': {
      id: '/_authenticated/_catechist/_admin/academic-years'
      path: '/academic-years'
      fullPath: '/academic-years'
      preLoaderRoute: typeof AuthenticatedCatechistAdminAcademicYearsRouteImport
      parentRoute: typeof AuthenticatedCatechistAdminRoute
    }
    '/_authenticated/_catechist/students_/$id_/edit': {
      id: '/_authenticated/_catechist/students_/$id_/edit'
      path: '/students/$id/edit'
      fullPath: '/students/$id/edit'
      preLoaderRoute: typeof AuthenticatedCatechistStudentsIdEditRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/students_/$id_/attendance': {
      id: '/_authenticated/_catechist/students_/$id_/attendance'
      path: '/students/$id/attendance'
      fullPath: '/students/$id/attendance'
      preLoaderRoute: typeof AuthenticatedCatechistStudentsIdAttendanceRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/classes_/$id_/edit': {
      id: '/_authenticated/_catechist/classes_/$id_/edit'
      path: '/classes/$id/edit'
      fullPath: '/classes/$id/edit'
      preLoaderRoute: typeof AuthenticatedCatechistClassesIdEditRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/catechists_/$id_/edit': {
      id: '/_authenticated/_catechist/catechists_/$id_/edit'
      path: '/catechists/$id/edit'
      fullPath: '/catechists/$id/edit'
      preLoaderRoute: typeof AuthenticatedCatechistCatechistsIdEditRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/branches_/$id_/edit': {
      id: '/_authenticated/_catechist/branches_/$id_/edit'
      path: '/branches/$id/edit'
      fullPath: '/branches/$id/edit'
      preLoaderRoute: typeof AuthenticatedCatechistBranchesIdEditRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/_admin/academic-years_/setup': {
      id: '/_authenticated/_catechist/_admin/academic-years_/setup'
      path: '/academic-years/setup'
      fullPath: '/academic-years/setup'
      preLoaderRoute: typeof AuthenticatedCatechistAdminAcademicYearsSetupRouteImport
      parentRoute: typeof AuthenticatedCatechistAdminRoute
    }
    '/_authenticated/_catechist/_admin/academic-years_/create': {
      id: '/_authenticated/_catechist/_admin/academic-years_/create'
      path: '/academic-years/create'
      fullPath: '/academic-years/create'
      preLoaderRoute: typeof AuthenticatedCatechistAdminAcademicYearsCreateRouteImport
      parentRoute: typeof AuthenticatedCatechistAdminRoute
    }
    '/_authenticated/_catechist/_admin/academic-years_/$id': {
      id: '/_authenticated/_catechist/_admin/academic-years_/$id'
      path: '/academic-years/$id'
      fullPath: '/academic-years/$id'
      preLoaderRoute: typeof AuthenticatedCatechistAdminAcademicYearsIdRouteImport
      parentRoute: typeof AuthenticatedCatechistAdminRoute
    }
    '/_authenticated/_catechist/classes_/$id_/sessions_/create': {
      id: '/_authenticated/_catechist/classes_/$id_/sessions_/create'
      path: '/classes/$id/sessions/create'
      fullPath: '/classes/$id/sessions/create'
      preLoaderRoute: typeof AuthenticatedCatechistClassesIdSessionsCreateRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/classes_/$id_/exams_/create': {
      id: '/_authenticated/_catechist/classes_/$id_/exams_/create'
      path: '/classes/$id/exams/create'
      fullPath: '/classes/$id/exams/create'
      preLoaderRoute: typeof AuthenticatedCatechistClassesIdExamsCreateRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/_admin/academic-years_/$id_/edit': {
      id: '/_authenticated/_catechist/_admin/academic-years_/$id_/edit'
      path: '/academic-years/$id/edit'
      fullPath: '/academic-years/$id/edit'
      preLoaderRoute: typeof AuthenticatedCatechistAdminAcademicYearsIdEditRouteImport
      parentRoute: typeof AuthenticatedCatechistAdminRoute
    }
  }
}

interface AuthenticatedCatechistAdminRouteChildren {
  AuthenticatedCatechistAdminAcademicYearsRoute: typeof AuthenticatedCatechistAdminAcademicYearsRoute
  AuthenticatedCatechistAdminAppConfigRoute: typeof AuthenticatedCatechistAdminAppConfigRoute
  AuthenticatedCatechistAdminCatechistAccountsRoute: typeof AuthenticatedCatechistAdminCatechistAccountsRoute
  AuthenticatedCatechistAdminImportRoute: typeof AuthenticatedCatechistAdminImportRoute
  AuthenticatedCatechistAdminStudentAccountsRoute: typeof AuthenticatedCatechistAdminStudentAccountsRoute
  AuthenticatedCatechistAdminAcademicYearsIdRoute: typeof AuthenticatedCatechistAdminAcademicYearsIdRoute
  AuthenticatedCatechistAdminAcademicYearsCreateRoute: typeof AuthenticatedCatechistAdminAcademicYearsCreateRoute
  AuthenticatedCatechistAdminAcademicYearsSetupRoute: typeof AuthenticatedCatechistAdminAcademicYearsSetupRoute
  AuthenticatedCatechistAdminAcademicYearsIdEditRoute: typeof AuthenticatedCatechistAdminAcademicYearsIdEditRoute
}

const AuthenticatedCatechistAdminRouteChildren: AuthenticatedCatechistAdminRouteChildren =
  {
    AuthenticatedCatechistAdminAcademicYearsRoute:
      AuthenticatedCatechistAdminAcademicYearsRoute,
    AuthenticatedCatechistAdminAppConfigRoute:
      AuthenticatedCatechistAdminAppConfigRoute,
    AuthenticatedCatechistAdminCatechistAccountsRoute:
      AuthenticatedCatechistAdminCatechistAccountsRoute,
    AuthenticatedCatechistAdminImportRoute:
      AuthenticatedCatechistAdminImportRoute,
    AuthenticatedCatechistAdminStudentAccountsRoute:
      AuthenticatedCatechistAdminStudentAccountsRoute,
    AuthenticatedCatechistAdminAcademicYearsIdRoute:
      AuthenticatedCatechistAdminAcademicYearsIdRoute,
    AuthenticatedCatechistAdminAcademicYearsCreateRoute:
      AuthenticatedCatechistAdminAcademicYearsCreateRoute,
    AuthenticatedCatechistAdminAcademicYearsSetupRoute:
      AuthenticatedCatechistAdminAcademicYearsSetupRoute,
    AuthenticatedCatechistAdminAcademicYearsIdEditRoute:
      AuthenticatedCatechistAdminAcademicYearsIdEditRoute,
  }

const AuthenticatedCatechistAdminRouteWithChildren =
  AuthenticatedCatechistAdminRoute._addFileChildren(
    AuthenticatedCatechistAdminRouteChildren,
  )

interface AuthenticatedCatechistRouteChildren {
  AuthenticatedCatechistAdminRoute: typeof AuthenticatedCatechistAdminRouteWithChildren
  AuthenticatedCatechistAssignmentsRoute: typeof AuthenticatedCatechistAssignmentsRoute
  AuthenticatedCatechistAttendanceRoute: typeof AuthenticatedCatechistAttendanceRoute
  AuthenticatedCatechistBranchesRoute: typeof AuthenticatedCatechistBranchesRoute
  AuthenticatedCatechistCalendarRoute: typeof AuthenticatedCatechistCalendarRoute
  AuthenticatedCatechistCalendarEventsRoute: typeof AuthenticatedCatechistCalendarEventsRoute
  AuthenticatedCatechistCatechistsRoute: typeof AuthenticatedCatechistCatechistsRoute
  AuthenticatedCatechistClassesRoute: typeof AuthenticatedCatechistClassesRoute
  AuthenticatedCatechistStudentsRoute: typeof AuthenticatedCatechistStudentsRoute
  AuthenticatedCatechistAssignmentsEditRoute: typeof AuthenticatedCatechistAssignmentsEditRoute
  AuthenticatedCatechistBranchesIdRoute: typeof AuthenticatedCatechistBranchesIdRoute
  AuthenticatedCatechistBranchesCreateRoute: typeof AuthenticatedCatechistBranchesCreateRoute
  AuthenticatedCatechistCatechistsIdRoute: typeof AuthenticatedCatechistCatechistsIdRoute
  AuthenticatedCatechistCatechistsCreateRoute: typeof AuthenticatedCatechistCatechistsCreateRoute
  AuthenticatedCatechistClassesIdRoute: typeof AuthenticatedCatechistClassesIdRoute
  AuthenticatedCatechistClassesBulkCreateRoute: typeof AuthenticatedCatechistClassesBulkCreateRoute
  AuthenticatedCatechistClassesCreateRoute: typeof AuthenticatedCatechistClassesCreateRoute
  AuthenticatedCatechistReportsAcademicYearReportRoute: typeof AuthenticatedCatechistReportsAcademicYearReportRoute
  AuthenticatedCatechistReportsAcademicYearsComparisonRoute: typeof AuthenticatedCatechistReportsAcademicYearsComparisonRoute
  AuthenticatedCatechistReportsMassExtraAttendanceRoute: typeof AuthenticatedCatechistReportsMassExtraAttendanceRoute
  AuthenticatedCatechistStudentsIdRoute: typeof AuthenticatedCatechistStudentsIdRoute
  AuthenticatedCatechistStudentsCreateRoute: typeof AuthenticatedCatechistStudentsCreateRoute
  AuthenticatedCatechistStudentsPromoteRoute: typeof AuthenticatedCatechistStudentsPromoteRoute
  AuthenticatedCatechistBranchesIdEditRoute: typeof AuthenticatedCatechistBranchesIdEditRoute
  AuthenticatedCatechistCatechistsIdEditRoute: typeof AuthenticatedCatechistCatechistsIdEditRoute
  AuthenticatedCatechistClassesIdEditRoute: typeof AuthenticatedCatechistClassesIdEditRoute
  AuthenticatedCatechistStudentsIdAttendanceRoute: typeof AuthenticatedCatechistStudentsIdAttendanceRoute
  AuthenticatedCatechistStudentsIdEditRoute: typeof AuthenticatedCatechistStudentsIdEditRoute
  AuthenticatedCatechistClassesIdExamsCreateRoute: typeof AuthenticatedCatechistClassesIdExamsCreateRoute
  AuthenticatedCatechistClassesIdSessionsCreateRoute: typeof AuthenticatedCatechistClassesIdSessionsCreateRoute
}

const AuthenticatedCatechistRouteChildren: AuthenticatedCatechistRouteChildren =
  {
    AuthenticatedCatechistAdminRoute:
      AuthenticatedCatechistAdminRouteWithChildren,
    AuthenticatedCatechistAssignmentsRoute:
      AuthenticatedCatechistAssignmentsRoute,
    AuthenticatedCatechistAttendanceRoute:
      AuthenticatedCatechistAttendanceRoute,
    AuthenticatedCatechistBranchesRoute: AuthenticatedCatechistBranchesRoute,
    AuthenticatedCatechistCalendarRoute: AuthenticatedCatechistCalendarRoute,
    AuthenticatedCatechistCalendarEventsRoute:
      AuthenticatedCatechistCalendarEventsRoute,
    AuthenticatedCatechistCatechistsRoute:
      AuthenticatedCatechistCatechistsRoute,
    AuthenticatedCatechistClassesRoute: AuthenticatedCatechistClassesRoute,
    AuthenticatedCatechistStudentsRoute: AuthenticatedCatechistStudentsRoute,
    AuthenticatedCatechistAssignmentsEditRoute:
      AuthenticatedCatechistAssignmentsEditRoute,
    AuthenticatedCatechistBranchesIdRoute:
      AuthenticatedCatechistBranchesIdRoute,
    AuthenticatedCatechistBranchesCreateRoute:
      AuthenticatedCatechistBranchesCreateRoute,
    AuthenticatedCatechistCatechistsIdRoute:
      AuthenticatedCatechistCatechistsIdRoute,
    AuthenticatedCatechistCatechistsCreateRoute:
      AuthenticatedCatechistCatechistsCreateRoute,
    AuthenticatedCatechistClassesIdRoute: AuthenticatedCatechistClassesIdRoute,
    AuthenticatedCatechistClassesBulkCreateRoute:
      AuthenticatedCatechistClassesBulkCreateRoute,
    AuthenticatedCatechistClassesCreateRoute:
      AuthenticatedCatechistClassesCreateRoute,
    AuthenticatedCatechistReportsAcademicYearReportRoute:
      AuthenticatedCatechistReportsAcademicYearReportRoute,
    AuthenticatedCatechistReportsAcademicYearsComparisonRoute:
      AuthenticatedCatechistReportsAcademicYearsComparisonRoute,
    AuthenticatedCatechistReportsMassExtraAttendanceRoute:
      AuthenticatedCatechistReportsMassExtraAttendanceRoute,
    AuthenticatedCatechistStudentsIdRoute:
      AuthenticatedCatechistStudentsIdRoute,
    AuthenticatedCatechistStudentsCreateRoute:
      AuthenticatedCatechistStudentsCreateRoute,
    AuthenticatedCatechistStudentsPromoteRoute:
      AuthenticatedCatechistStudentsPromoteRoute,
    AuthenticatedCatechistBranchesIdEditRoute:
      AuthenticatedCatechistBranchesIdEditRoute,
    AuthenticatedCatechistCatechistsIdEditRoute:
      AuthenticatedCatechistCatechistsIdEditRoute,
    AuthenticatedCatechistClassesIdEditRoute:
      AuthenticatedCatechistClassesIdEditRoute,
    AuthenticatedCatechistStudentsIdAttendanceRoute:
      AuthenticatedCatechistStudentsIdAttendanceRoute,
    AuthenticatedCatechistStudentsIdEditRoute:
      AuthenticatedCatechistStudentsIdEditRoute,
    AuthenticatedCatechistClassesIdExamsCreateRoute:
      AuthenticatedCatechistClassesIdExamsCreateRoute,
    AuthenticatedCatechistClassesIdSessionsCreateRoute:
      AuthenticatedCatechistClassesIdSessionsCreateRoute,
  }

const AuthenticatedCatechistRouteWithChildren =
  AuthenticatedCatechistRoute._addFileChildren(
    AuthenticatedCatechistRouteChildren,
  )

interface AuthenticatedStudentRouteChildren {
  AuthenticatedStudentMyAttendanceRoute: typeof AuthenticatedStudentMyAttendanceRoute
}

const AuthenticatedStudentRouteChildren: AuthenticatedStudentRouteChildren = {
  AuthenticatedStudentMyAttendanceRoute: AuthenticatedStudentMyAttendanceRoute,
}

const AuthenticatedStudentRouteWithChildren =
  AuthenticatedStudentRoute._addFileChildren(AuthenticatedStudentRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedCatechistRoute: typeof AuthenticatedCatechistRouteWithChildren
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRouteWithChildren
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCatechistRoute: AuthenticatedCatechistRouteWithChildren,
  AuthenticatedStudentRoute: AuthenticatedStudentRouteWithChildren,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface HelpRouteChildren {
  HelpRoleRoute: typeof HelpRoleRoute
  HelpIndexRoute: typeof HelpIndexRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpRoleRoute: HelpRoleRoute,
  HelpIndexRoute: HelpIndexRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AnotherPageRoute: AnotherPageRoute,
  HelpRoute: HelpRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  ClassesIdPhotoboothRoute: ClassesIdPhotoboothRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
