/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AnotherPageRouteImport } from './routes/anotherPage'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedCatechistRouteImport } from './routes/_authenticated/_catechist'
import { Route as AuthenticatedCatechistStudentsRouteImport } from './routes/_authenticated/_catechist/students'
import { Route as AuthenticatedCatechistClassesRouteImport } from './routes/_authenticated/_catechist/classes'
import { Route as AuthenticatedCatechistCatechistsRouteImport } from './routes/_authenticated/_catechist/catechists'
import { Route as AuthenticatedCatechistBranchesRouteImport } from './routes/_authenticated/_catechist/branches'
import { Route as AuthenticatedCatechistAssignmentsRouteImport } from './routes/_authenticated/_catechist/assignments'
import { Route as AuthenticatedCatechistAdminRouteImport } from './routes/_authenticated/_catechist/_admin'
import { Route as AuthenticatedCatechistStudentsCreateRouteImport } from './routes/_authenticated/_catechist/students_.create'
import { Route as AuthenticatedCatechistStudentsIdRouteImport } from './routes/_authenticated/_catechist/students_.$id'
import { Route as AuthenticatedCatechistClassesCreateRouteImport } from './routes/_authenticated/_catechist/classes_.create'
import { Route as AuthenticatedCatechistClassesBulkCreateRouteImport } from './routes/_authenticated/_catechist/classes_.bulk-create'
import { Route as AuthenticatedCatechistClassesIdRouteImport } from './routes/_authenticated/_catechist/classes_.$id'
import { Route as AuthenticatedCatechistCatechistsCreateRouteImport } from './routes/_authenticated/_catechist/catechists_.create'
import { Route as AuthenticatedCatechistCatechistsIdRouteImport } from './routes/_authenticated/_catechist/catechists_.$id'
import { Route as AuthenticatedCatechistBranchesCreateRouteImport } from './routes/_authenticated/_catechist/branches_.create'
import { Route as AuthenticatedCatechistBranchesIdRouteImport } from './routes/_authenticated/_catechist/branches_.$id'
import { Route as AuthenticatedCatechistAssignmentsEditRouteImport } from './routes/_authenticated/_catechist/assignments_.edit'
import { Route as AuthenticatedCatechistAdminImportRouteImport } from './routes/_authenticated/_catechist/_admin/import'
import { Route as AuthenticatedCatechistAdminAcademicYearsRouteImport } from './routes/_authenticated/_catechist/_admin/academic-years'
import { Route as AuthenticatedCatechistStudentsIdEditRouteImport } from './routes/_authenticated/_catechist/students_.$id_.edit'
import { Route as AuthenticatedCatechistClassesIdEditRouteImport } from './routes/_authenticated/_catechist/classes_.$id_.edit'
import { Route as AuthenticatedCatechistCatechistsIdEditRouteImport } from './routes/_authenticated/_catechist/catechists_.$id_.edit'
import { Route as AuthenticatedCatechistBranchesIdEditRouteImport } from './routes/_authenticated/_catechist/branches_.$id_.edit'
import { Route as AuthenticatedCatechistAdminAdminStudentAccountsRouteImport } from './routes/_authenticated/_catechist/_admin/admin.student-accounts'
import { Route as AuthenticatedCatechistAdminAdminCatechistAccountsRouteImport } from './routes/_authenticated/_catechist/_admin/admin.catechist-accounts'
import { Route as AuthenticatedCatechistAdminAcademicYearsCreateRouteImport } from './routes/_authenticated/_catechist/_admin/academic-years_.create'
import { Route as AuthenticatedCatechistAdminAcademicYearsIdRouteImport } from './routes/_authenticated/_catechist/_admin/academic-years_.$id'
import { Route as AuthenticatedCatechistClassesIdSessionsCreateRouteImport } from './routes/_authenticated/_catechist/classes_.$id_.sessions_.create'
import { Route as AuthenticatedCatechistClassesIdExamsCreateRouteImport } from './routes/_authenticated/_catechist/classes_.$id_.exams_.create'
import { Route as AuthenticatedCatechistAdminAcademicYearsIdEditRouteImport } from './routes/_authenticated/_catechist/_admin/academic-years_.$id_.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnotherPageRoute = AnotherPageRouteImport.update({
  id: '/anotherPage',
  path: '/anotherPage',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatechistRoute = AuthenticatedCatechistRouteImport.update({
  id: '/_catechist',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCatechistStudentsRoute =
  AuthenticatedCatechistStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistClassesRoute =
  AuthenticatedCatechistClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistCatechistsRoute =
  AuthenticatedCatechistCatechistsRouteImport.update({
    id: '/catechists',
    path: '/catechists',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistBranchesRoute =
  AuthenticatedCatechistBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistAssignmentsRoute =
  AuthenticatedCatechistAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistAdminRoute =
  AuthenticatedCatechistAdminRouteImport.update({
    id: '/_admin',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistStudentsCreateRoute =
  AuthenticatedCatechistStudentsCreateRouteImport.update({
    id: '/students_/create',
    path: '/students/create',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistStudentsIdRoute =
  AuthenticatedCatechistStudentsIdRouteImport.update({
    id: '/students_/$id',
    path: '/students/$id',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistClassesCreateRoute =
  AuthenticatedCatechistClassesCreateRouteImport.update({
    id: '/classes_/create',
    path: '/classes/create',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistClassesBulkCreateRoute =
  AuthenticatedCatechistClassesBulkCreateRouteImport.update({
    id: '/classes_/bulk-create',
    path: '/classes/bulk-create',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistClassesIdRoute =
  AuthenticatedCatechistClassesIdRouteImport.update({
    id: '/classes_/$id',
    path: '/classes/$id',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistCatechistsCreateRoute =
  AuthenticatedCatechistCatechistsCreateRouteImport.update({
    id: '/catechists_/create',
    path: '/catechists/create',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistCatechistsIdRoute =
  AuthenticatedCatechistCatechistsIdRouteImport.update({
    id: '/catechists_/$id',
    path: '/catechists/$id',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistBranchesCreateRoute =
  AuthenticatedCatechistBranchesCreateRouteImport.update({
    id: '/branches_/create',
    path: '/branches/create',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistBranchesIdRoute =
  AuthenticatedCatechistBranchesIdRouteImport.update({
    id: '/branches_/$id',
    path: '/branches/$id',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistAssignmentsEditRoute =
  AuthenticatedCatechistAssignmentsEditRouteImport.update({
    id: '/assignments_/edit',
    path: '/assignments/edit',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistAdminImportRoute =
  AuthenticatedCatechistAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedCatechistAdminRoute,
  } as any)
const AuthenticatedCatechistAdminAcademicYearsRoute =
  AuthenticatedCatechistAdminAcademicYearsRouteImport.update({
    id: '/academic-years',
    path: '/academic-years',
    getParentRoute: () => AuthenticatedCatechistAdminRoute,
  } as any)
const AuthenticatedCatechistStudentsIdEditRoute =
  AuthenticatedCatechistStudentsIdEditRouteImport.update({
    id: '/students_/$id_/edit',
    path: '/students/$id/edit',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistClassesIdEditRoute =
  AuthenticatedCatechistClassesIdEditRouteImport.update({
    id: '/classes_/$id_/edit',
    path: '/classes/$id/edit',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistCatechistsIdEditRoute =
  AuthenticatedCatechistCatechistsIdEditRouteImport.update({
    id: '/catechists_/$id_/edit',
    path: '/catechists/$id/edit',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistBranchesIdEditRoute =
  AuthenticatedCatechistBranchesIdEditRouteImport.update({
    id: '/branches_/$id_/edit',
    path: '/branches/$id/edit',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistAdminAdminStudentAccountsRoute =
  AuthenticatedCatechistAdminAdminStudentAccountsRouteImport.update({
    id: '/admin/student-accounts',
    path: '/admin/student-accounts',
    getParentRoute: () => AuthenticatedCatechistAdminRoute,
  } as any)
const AuthenticatedCatechistAdminAdminCatechistAccountsRoute =
  AuthenticatedCatechistAdminAdminCatechistAccountsRouteImport.update({
    id: '/admin/catechist-accounts',
    path: '/admin/catechist-accounts',
    getParentRoute: () => AuthenticatedCatechistAdminRoute,
  } as any)
const AuthenticatedCatechistAdminAcademicYearsCreateRoute =
  AuthenticatedCatechistAdminAcademicYearsCreateRouteImport.update({
    id: '/academic-years_/create',
    path: '/academic-years/create',
    getParentRoute: () => AuthenticatedCatechistAdminRoute,
  } as any)
const AuthenticatedCatechistAdminAcademicYearsIdRoute =
  AuthenticatedCatechistAdminAcademicYearsIdRouteImport.update({
    id: '/academic-years_/$id',
    path: '/academic-years/$id',
    getParentRoute: () => AuthenticatedCatechistAdminRoute,
  } as any)
const AuthenticatedCatechistClassesIdSessionsCreateRoute =
  AuthenticatedCatechistClassesIdSessionsCreateRouteImport.update({
    id: '/classes_/$id_/sessions_/create',
    path: '/classes/$id/sessions/create',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistClassesIdExamsCreateRoute =
  AuthenticatedCatechistClassesIdExamsCreateRouteImport.update({
    id: '/classes_/$id_/exams_/create',
    path: '/classes/$id/exams/create',
    getParentRoute: () => AuthenticatedCatechistRoute,
  } as any)
const AuthenticatedCatechistAdminAcademicYearsIdEditRoute =
  AuthenticatedCatechistAdminAcademicYearsIdEditRouteImport.update({
    id: '/academic-years_/$id_/edit',
    path: '/academic-years/$id/edit',
    getParentRoute: () => AuthenticatedCatechistAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anotherPage': typeof AnotherPageRoute
  '/login': typeof LoginRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/assignments': typeof AuthenticatedCatechistAssignmentsRoute
  '/branches': typeof AuthenticatedCatechistBranchesRoute
  '/catechists': typeof AuthenticatedCatechistCatechistsRoute
  '/classes': typeof AuthenticatedCatechistClassesRoute
  '/students': typeof AuthenticatedCatechistStudentsRoute
  '/academic-years': typeof AuthenticatedCatechistAdminAcademicYearsRoute
  '/import': typeof AuthenticatedCatechistAdminImportRoute
  '/assignments/edit': typeof AuthenticatedCatechistAssignmentsEditRoute
  '/branches/$id': typeof AuthenticatedCatechistBranchesIdRoute
  '/branches/create': typeof AuthenticatedCatechistBranchesCreateRoute
  '/catechists/$id': typeof AuthenticatedCatechistCatechistsIdRoute
  '/catechists/create': typeof AuthenticatedCatechistCatechistsCreateRoute
  '/classes/$id': typeof AuthenticatedCatechistClassesIdRoute
  '/classes/bulk-create': typeof AuthenticatedCatechistClassesBulkCreateRoute
  '/classes/create': typeof AuthenticatedCatechistClassesCreateRoute
  '/students/$id': typeof AuthenticatedCatechistStudentsIdRoute
  '/students/create': typeof AuthenticatedCatechistStudentsCreateRoute
  '/academic-years/$id': typeof AuthenticatedCatechistAdminAcademicYearsIdRoute
  '/academic-years/create': typeof AuthenticatedCatechistAdminAcademicYearsCreateRoute
  '/admin/catechist-accounts': typeof AuthenticatedCatechistAdminAdminCatechistAccountsRoute
  '/admin/student-accounts': typeof AuthenticatedCatechistAdminAdminStudentAccountsRoute
  '/branches/$id/edit': typeof AuthenticatedCatechistBranchesIdEditRoute
  '/catechists/$id/edit': typeof AuthenticatedCatechistCatechistsIdEditRoute
  '/classes/$id/edit': typeof AuthenticatedCatechistClassesIdEditRoute
  '/students/$id/edit': typeof AuthenticatedCatechistStudentsIdEditRoute
  '/academic-years/$id/edit': typeof AuthenticatedCatechistAdminAcademicYearsIdEditRoute
  '/classes/$id/exams/create': typeof AuthenticatedCatechistClassesIdExamsCreateRoute
  '/classes/$id/sessions/create': typeof AuthenticatedCatechistClassesIdSessionsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anotherPage': typeof AnotherPageRoute
  '/login': typeof LoginRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/assignments': typeof AuthenticatedCatechistAssignmentsRoute
  '/branches': typeof AuthenticatedCatechistBranchesRoute
  '/catechists': typeof AuthenticatedCatechistCatechistsRoute
  '/classes': typeof AuthenticatedCatechistClassesRoute
  '/students': typeof AuthenticatedCatechistStudentsRoute
  '/academic-years': typeof AuthenticatedCatechistAdminAcademicYearsRoute
  '/import': typeof AuthenticatedCatechistAdminImportRoute
  '/assignments/edit': typeof AuthenticatedCatechistAssignmentsEditRoute
  '/branches/$id': typeof AuthenticatedCatechistBranchesIdRoute
  '/branches/create': typeof AuthenticatedCatechistBranchesCreateRoute
  '/catechists/$id': typeof AuthenticatedCatechistCatechistsIdRoute
  '/catechists/create': typeof AuthenticatedCatechistCatechistsCreateRoute
  '/classes/$id': typeof AuthenticatedCatechistClassesIdRoute
  '/classes/bulk-create': typeof AuthenticatedCatechistClassesBulkCreateRoute
  '/classes/create': typeof AuthenticatedCatechistClassesCreateRoute
  '/students/$id': typeof AuthenticatedCatechistStudentsIdRoute
  '/students/create': typeof AuthenticatedCatechistStudentsCreateRoute
  '/academic-years/$id': typeof AuthenticatedCatechistAdminAcademicYearsIdRoute
  '/academic-years/create': typeof AuthenticatedCatechistAdminAcademicYearsCreateRoute
  '/admin/catechist-accounts': typeof AuthenticatedCatechistAdminAdminCatechistAccountsRoute
  '/admin/student-accounts': typeof AuthenticatedCatechistAdminAdminStudentAccountsRoute
  '/branches/$id/edit': typeof AuthenticatedCatechistBranchesIdEditRoute
  '/catechists/$id/edit': typeof AuthenticatedCatechistCatechistsIdEditRoute
  '/classes/$id/edit': typeof AuthenticatedCatechistClassesIdEditRoute
  '/students/$id/edit': typeof AuthenticatedCatechistStudentsIdEditRoute
  '/academic-years/$id/edit': typeof AuthenticatedCatechistAdminAcademicYearsIdEditRoute
  '/classes/$id/exams/create': typeof AuthenticatedCatechistClassesIdExamsCreateRoute
  '/classes/$id/sessions/create': typeof AuthenticatedCatechistClassesIdSessionsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/anotherPage': typeof AnotherPageRoute
  '/login': typeof LoginRoute
  '/_authenticated/_catechist': typeof AuthenticatedCatechistRouteWithChildren
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/_catechist/_admin': typeof AuthenticatedCatechistAdminRouteWithChildren
  '/_authenticated/_catechist/assignments': typeof AuthenticatedCatechistAssignmentsRoute
  '/_authenticated/_catechist/branches': typeof AuthenticatedCatechistBranchesRoute
  '/_authenticated/_catechist/catechists': typeof AuthenticatedCatechistCatechistsRoute
  '/_authenticated/_catechist/classes': typeof AuthenticatedCatechistClassesRoute
  '/_authenticated/_catechist/students': typeof AuthenticatedCatechistStudentsRoute
  '/_authenticated/_catechist/_admin/academic-years': typeof AuthenticatedCatechistAdminAcademicYearsRoute
  '/_authenticated/_catechist/_admin/import': typeof AuthenticatedCatechistAdminImportRoute
  '/_authenticated/_catechist/assignments_/edit': typeof AuthenticatedCatechistAssignmentsEditRoute
  '/_authenticated/_catechist/branches_/$id': typeof AuthenticatedCatechistBranchesIdRoute
  '/_authenticated/_catechist/branches_/create': typeof AuthenticatedCatechistBranchesCreateRoute
  '/_authenticated/_catechist/catechists_/$id': typeof AuthenticatedCatechistCatechistsIdRoute
  '/_authenticated/_catechist/catechists_/create': typeof AuthenticatedCatechistCatechistsCreateRoute
  '/_authenticated/_catechist/classes_/$id': typeof AuthenticatedCatechistClassesIdRoute
  '/_authenticated/_catechist/classes_/bulk-create': typeof AuthenticatedCatechistClassesBulkCreateRoute
  '/_authenticated/_catechist/classes_/create': typeof AuthenticatedCatechistClassesCreateRoute
  '/_authenticated/_catechist/students_/$id': typeof AuthenticatedCatechistStudentsIdRoute
  '/_authenticated/_catechist/students_/create': typeof AuthenticatedCatechistStudentsCreateRoute
  '/_authenticated/_catechist/_admin/academic-years_/$id': typeof AuthenticatedCatechistAdminAcademicYearsIdRoute
  '/_authenticated/_catechist/_admin/academic-years_/create': typeof AuthenticatedCatechistAdminAcademicYearsCreateRoute
  '/_authenticated/_catechist/_admin/admin/catechist-accounts': typeof AuthenticatedCatechistAdminAdminCatechistAccountsRoute
  '/_authenticated/_catechist/_admin/admin/student-accounts': typeof AuthenticatedCatechistAdminAdminStudentAccountsRoute
  '/_authenticated/_catechist/branches_/$id_/edit': typeof AuthenticatedCatechistBranchesIdEditRoute
  '/_authenticated/_catechist/catechists_/$id_/edit': typeof AuthenticatedCatechistCatechistsIdEditRoute
  '/_authenticated/_catechist/classes_/$id_/edit': typeof AuthenticatedCatechistClassesIdEditRoute
  '/_authenticated/_catechist/students_/$id_/edit': typeof AuthenticatedCatechistStudentsIdEditRoute
  '/_authenticated/_catechist/_admin/academic-years_/$id_/edit': typeof AuthenticatedCatechistAdminAcademicYearsIdEditRoute
  '/_authenticated/_catechist/classes_/$id_/exams_/create': typeof AuthenticatedCatechistClassesIdExamsCreateRoute
  '/_authenticated/_catechist/classes_/$id_/sessions_/create': typeof AuthenticatedCatechistClassesIdSessionsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anotherPage'
    | '/login'
    | '/change-password'
    | '/dashboard'
    | '/profile'
    | '/assignments'
    | '/branches'
    | '/catechists'
    | '/classes'
    | '/students'
    | '/academic-years'
    | '/import'
    | '/assignments/edit'
    | '/branches/$id'
    | '/branches/create'
    | '/catechists/$id'
    | '/catechists/create'
    | '/classes/$id'
    | '/classes/bulk-create'
    | '/classes/create'
    | '/students/$id'
    | '/students/create'
    | '/academic-years/$id'
    | '/academic-years/create'
    | '/admin/catechist-accounts'
    | '/admin/student-accounts'
    | '/branches/$id/edit'
    | '/catechists/$id/edit'
    | '/classes/$id/edit'
    | '/students/$id/edit'
    | '/academic-years/$id/edit'
    | '/classes/$id/exams/create'
    | '/classes/$id/sessions/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anotherPage'
    | '/login'
    | '/change-password'
    | '/dashboard'
    | '/profile'
    | '/assignments'
    | '/branches'
    | '/catechists'
    | '/classes'
    | '/students'
    | '/academic-years'
    | '/import'
    | '/assignments/edit'
    | '/branches/$id'
    | '/branches/create'
    | '/catechists/$id'
    | '/catechists/create'
    | '/classes/$id'
    | '/classes/bulk-create'
    | '/classes/create'
    | '/students/$id'
    | '/students/create'
    | '/academic-years/$id'
    | '/academic-years/create'
    | '/admin/catechist-accounts'
    | '/admin/student-accounts'
    | '/branches/$id/edit'
    | '/catechists/$id/edit'
    | '/classes/$id/edit'
    | '/students/$id/edit'
    | '/academic-years/$id/edit'
    | '/classes/$id/exams/create'
    | '/classes/$id/sessions/create'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/anotherPage'
    | '/login'
    | '/_authenticated/_catechist'
    | '/_authenticated/change-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/_catechist/_admin'
    | '/_authenticated/_catechist/assignments'
    | '/_authenticated/_catechist/branches'
    | '/_authenticated/_catechist/catechists'
    | '/_authenticated/_catechist/classes'
    | '/_authenticated/_catechist/students'
    | '/_authenticated/_catechist/_admin/academic-years'
    | '/_authenticated/_catechist/_admin/import'
    | '/_authenticated/_catechist/assignments_/edit'
    | '/_authenticated/_catechist/branches_/$id'
    | '/_authenticated/_catechist/branches_/create'
    | '/_authenticated/_catechist/catechists_/$id'
    | '/_authenticated/_catechist/catechists_/create'
    | '/_authenticated/_catechist/classes_/$id'
    | '/_authenticated/_catechist/classes_/bulk-create'
    | '/_authenticated/_catechist/classes_/create'
    | '/_authenticated/_catechist/students_/$id'
    | '/_authenticated/_catechist/students_/create'
    | '/_authenticated/_catechist/_admin/academic-years_/$id'
    | '/_authenticated/_catechist/_admin/academic-years_/create'
    | '/_authenticated/_catechist/_admin/admin/catechist-accounts'
    | '/_authenticated/_catechist/_admin/admin/student-accounts'
    | '/_authenticated/_catechist/branches_/$id_/edit'
    | '/_authenticated/_catechist/catechists_/$id_/edit'
    | '/_authenticated/_catechist/classes_/$id_/edit'
    | '/_authenticated/_catechist/students_/$id_/edit'
    | '/_authenticated/_catechist/_admin/academic-years_/$id_/edit'
    | '/_authenticated/_catechist/classes_/$id_/exams_/create'
    | '/_authenticated/_catechist/classes_/$id_/sessions_/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AnotherPageRoute: typeof AnotherPageRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anotherPage': {
      id: '/anotherPage'
      path: '/anotherPage'
      fullPath: '/anotherPage'
      preLoaderRoute: typeof AnotherPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_catechist': {
      id: '/_authenticated/_catechist'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedCatechistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_catechist/students': {
      id: '/_authenticated/_catechist/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedCatechistStudentsRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/classes': {
      id: '/_authenticated/_catechist/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedCatechistClassesRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/catechists': {
      id: '/_authenticated/_catechist/catechists'
      path: '/catechists'
      fullPath: '/catechists'
      preLoaderRoute: typeof AuthenticatedCatechistCatechistsRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/branches': {
      id: '/_authenticated/_catechist/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedCatechistBranchesRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/assignments': {
      id: '/_authenticated/_catechist/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedCatechistAssignmentsRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/_admin': {
      id: '/_authenticated/_catechist/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedCatechistAdminRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/students_/create': {
      id: '/_authenticated/_catechist/students_/create'
      path: '/students/create'
      fullPath: '/students/create'
      preLoaderRoute: typeof AuthenticatedCatechistStudentsCreateRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/students_/$id': {
      id: '/_authenticated/_catechist/students_/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AuthenticatedCatechistStudentsIdRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/classes_/create': {
      id: '/_authenticated/_catechist/classes_/create'
      path: '/classes/create'
      fullPath: '/classes/create'
      preLoaderRoute: typeof AuthenticatedCatechistClassesCreateRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/classes_/bulk-create': {
      id: '/_authenticated/_catechist/classes_/bulk-create'
      path: '/classes/bulk-create'
      fullPath: '/classes/bulk-create'
      preLoaderRoute: typeof AuthenticatedCatechistClassesBulkCreateRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/classes_/$id': {
      id: '/_authenticated/_catechist/classes_/$id'
      path: '/classes/$id'
      fullPath: '/classes/$id'
      preLoaderRoute: typeof AuthenticatedCatechistClassesIdRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/catechists_/create': {
      id: '/_authenticated/_catechist/catechists_/create'
      path: '/catechists/create'
      fullPath: '/catechists/create'
      preLoaderRoute: typeof AuthenticatedCatechistCatechistsCreateRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/catechists_/$id': {
      id: '/_authenticated/_catechist/catechists_/$id'
      path: '/catechists/$id'
      fullPath: '/catechists/$id'
      preLoaderRoute: typeof AuthenticatedCatechistCatechistsIdRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/branches_/create': {
      id: '/_authenticated/_catechist/branches_/create'
      path: '/branches/create'
      fullPath: '/branches/create'
      preLoaderRoute: typeof AuthenticatedCatechistBranchesCreateRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/branches_/$id': {
      id: '/_authenticated/_catechist/branches_/$id'
      path: '/branches/$id'
      fullPath: '/branches/$id'
      preLoaderRoute: typeof AuthenticatedCatechistBranchesIdRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/assignments_/edit': {
      id: '/_authenticated/_catechist/assignments_/edit'
      path: '/assignments/edit'
      fullPath: '/assignments/edit'
      preLoaderRoute: typeof AuthenticatedCatechistAssignmentsEditRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/_admin/import': {
      id: '/_authenticated/_catechist/_admin/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedCatechistAdminImportRouteImport
      parentRoute: typeof AuthenticatedCatechistAdminRoute
    }
    '/_authenticated/_catechist/_admin/academic-years': {
      id: '/_authenticated/_catechist/_admin/academic-years'
      path: '/academic-years'
      fullPath: '/academic-years'
      preLoaderRoute: typeof AuthenticatedCatechistAdminAcademicYearsRouteImport
      parentRoute: typeof AuthenticatedCatechistAdminRoute
    }
    '/_authenticated/_catechist/students_/$id_/edit': {
      id: '/_authenticated/_catechist/students_/$id_/edit'
      path: '/students/$id/edit'
      fullPath: '/students/$id/edit'
      preLoaderRoute: typeof AuthenticatedCatechistStudentsIdEditRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/classes_/$id_/edit': {
      id: '/_authenticated/_catechist/classes_/$id_/edit'
      path: '/classes/$id/edit'
      fullPath: '/classes/$id/edit'
      preLoaderRoute: typeof AuthenticatedCatechistClassesIdEditRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/catechists_/$id_/edit': {
      id: '/_authenticated/_catechist/catechists_/$id_/edit'
      path: '/catechists/$id/edit'
      fullPath: '/catechists/$id/edit'
      preLoaderRoute: typeof AuthenticatedCatechistCatechistsIdEditRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/branches_/$id_/edit': {
      id: '/_authenticated/_catechist/branches_/$id_/edit'
      path: '/branches/$id/edit'
      fullPath: '/branches/$id/edit'
      preLoaderRoute: typeof AuthenticatedCatechistBranchesIdEditRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/_admin/admin/student-accounts': {
      id: '/_authenticated/_catechist/_admin/admin/student-accounts'
      path: '/admin/student-accounts'
      fullPath: '/admin/student-accounts'
      preLoaderRoute: typeof AuthenticatedCatechistAdminAdminStudentAccountsRouteImport
      parentRoute: typeof AuthenticatedCatechistAdminRoute
    }
    '/_authenticated/_catechist/_admin/admin/catechist-accounts': {
      id: '/_authenticated/_catechist/_admin/admin/catechist-accounts'
      path: '/admin/catechist-accounts'
      fullPath: '/admin/catechist-accounts'
      preLoaderRoute: typeof AuthenticatedCatechistAdminAdminCatechistAccountsRouteImport
      parentRoute: typeof AuthenticatedCatechistAdminRoute
    }
    '/_authenticated/_catechist/_admin/academic-years_/create': {
      id: '/_authenticated/_catechist/_admin/academic-years_/create'
      path: '/academic-years/create'
      fullPath: '/academic-years/create'
      preLoaderRoute: typeof AuthenticatedCatechistAdminAcademicYearsCreateRouteImport
      parentRoute: typeof AuthenticatedCatechistAdminRoute
    }
    '/_authenticated/_catechist/_admin/academic-years_/$id': {
      id: '/_authenticated/_catechist/_admin/academic-years_/$id'
      path: '/academic-years/$id'
      fullPath: '/academic-years/$id'
      preLoaderRoute: typeof AuthenticatedCatechistAdminAcademicYearsIdRouteImport
      parentRoute: typeof AuthenticatedCatechistAdminRoute
    }
    '/_authenticated/_catechist/classes_/$id_/sessions_/create': {
      id: '/_authenticated/_catechist/classes_/$id_/sessions_/create'
      path: '/classes/$id/sessions/create'
      fullPath: '/classes/$id/sessions/create'
      preLoaderRoute: typeof AuthenticatedCatechistClassesIdSessionsCreateRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/classes_/$id_/exams_/create': {
      id: '/_authenticated/_catechist/classes_/$id_/exams_/create'
      path: '/classes/$id/exams/create'
      fullPath: '/classes/$id/exams/create'
      preLoaderRoute: typeof AuthenticatedCatechistClassesIdExamsCreateRouteImport
      parentRoute: typeof AuthenticatedCatechistRoute
    }
    '/_authenticated/_catechist/_admin/academic-years_/$id_/edit': {
      id: '/_authenticated/_catechist/_admin/academic-years_/$id_/edit'
      path: '/academic-years/$id/edit'
      fullPath: '/academic-years/$id/edit'
      preLoaderRoute: typeof AuthenticatedCatechistAdminAcademicYearsIdEditRouteImport
      parentRoute: typeof AuthenticatedCatechistAdminRoute
    }
  }
}

interface AuthenticatedCatechistAdminRouteChildren {
  AuthenticatedCatechistAdminAcademicYearsRoute: typeof AuthenticatedCatechistAdminAcademicYearsRoute
  AuthenticatedCatechistAdminImportRoute: typeof AuthenticatedCatechistAdminImportRoute
  AuthenticatedCatechistAdminAcademicYearsIdRoute: typeof AuthenticatedCatechistAdminAcademicYearsIdRoute
  AuthenticatedCatechistAdminAcademicYearsCreateRoute: typeof AuthenticatedCatechistAdminAcademicYearsCreateRoute
  AuthenticatedCatechistAdminAdminCatechistAccountsRoute: typeof AuthenticatedCatechistAdminAdminCatechistAccountsRoute
  AuthenticatedCatechistAdminAdminStudentAccountsRoute: typeof AuthenticatedCatechistAdminAdminStudentAccountsRoute
  AuthenticatedCatechistAdminAcademicYearsIdEditRoute: typeof AuthenticatedCatechistAdminAcademicYearsIdEditRoute
}

const AuthenticatedCatechistAdminRouteChildren: AuthenticatedCatechistAdminRouteChildren =
  {
    AuthenticatedCatechistAdminAcademicYearsRoute:
      AuthenticatedCatechistAdminAcademicYearsRoute,
    AuthenticatedCatechistAdminImportRoute:
      AuthenticatedCatechistAdminImportRoute,
    AuthenticatedCatechistAdminAcademicYearsIdRoute:
      AuthenticatedCatechistAdminAcademicYearsIdRoute,
    AuthenticatedCatechistAdminAcademicYearsCreateRoute:
      AuthenticatedCatechistAdminAcademicYearsCreateRoute,
    AuthenticatedCatechistAdminAdminCatechistAccountsRoute:
      AuthenticatedCatechistAdminAdminCatechistAccountsRoute,
    AuthenticatedCatechistAdminAdminStudentAccountsRoute:
      AuthenticatedCatechistAdminAdminStudentAccountsRoute,
    AuthenticatedCatechistAdminAcademicYearsIdEditRoute:
      AuthenticatedCatechistAdminAcademicYearsIdEditRoute,
  }

const AuthenticatedCatechistAdminRouteWithChildren =
  AuthenticatedCatechistAdminRoute._addFileChildren(
    AuthenticatedCatechistAdminRouteChildren,
  )

interface AuthenticatedCatechistRouteChildren {
  AuthenticatedCatechistAdminRoute: typeof AuthenticatedCatechistAdminRouteWithChildren
  AuthenticatedCatechistAssignmentsRoute: typeof AuthenticatedCatechistAssignmentsRoute
  AuthenticatedCatechistBranchesRoute: typeof AuthenticatedCatechistBranchesRoute
  AuthenticatedCatechistCatechistsRoute: typeof AuthenticatedCatechistCatechistsRoute
  AuthenticatedCatechistClassesRoute: typeof AuthenticatedCatechistClassesRoute
  AuthenticatedCatechistStudentsRoute: typeof AuthenticatedCatechistStudentsRoute
  AuthenticatedCatechistAssignmentsEditRoute: typeof AuthenticatedCatechistAssignmentsEditRoute
  AuthenticatedCatechistBranchesIdRoute: typeof AuthenticatedCatechistBranchesIdRoute
  AuthenticatedCatechistBranchesCreateRoute: typeof AuthenticatedCatechistBranchesCreateRoute
  AuthenticatedCatechistCatechistsIdRoute: typeof AuthenticatedCatechistCatechistsIdRoute
  AuthenticatedCatechistCatechistsCreateRoute: typeof AuthenticatedCatechistCatechistsCreateRoute
  AuthenticatedCatechistClassesIdRoute: typeof AuthenticatedCatechistClassesIdRoute
  AuthenticatedCatechistClassesBulkCreateRoute: typeof AuthenticatedCatechistClassesBulkCreateRoute
  AuthenticatedCatechistClassesCreateRoute: typeof AuthenticatedCatechistClassesCreateRoute
  AuthenticatedCatechistStudentsIdRoute: typeof AuthenticatedCatechistStudentsIdRoute
  AuthenticatedCatechistStudentsCreateRoute: typeof AuthenticatedCatechistStudentsCreateRoute
  AuthenticatedCatechistBranchesIdEditRoute: typeof AuthenticatedCatechistBranchesIdEditRoute
  AuthenticatedCatechistCatechistsIdEditRoute: typeof AuthenticatedCatechistCatechistsIdEditRoute
  AuthenticatedCatechistClassesIdEditRoute: typeof AuthenticatedCatechistClassesIdEditRoute
  AuthenticatedCatechistStudentsIdEditRoute: typeof AuthenticatedCatechistStudentsIdEditRoute
  AuthenticatedCatechistClassesIdExamsCreateRoute: typeof AuthenticatedCatechistClassesIdExamsCreateRoute
  AuthenticatedCatechistClassesIdSessionsCreateRoute: typeof AuthenticatedCatechistClassesIdSessionsCreateRoute
}

const AuthenticatedCatechistRouteChildren: AuthenticatedCatechistRouteChildren =
  {
    AuthenticatedCatechistAdminRoute:
      AuthenticatedCatechistAdminRouteWithChildren,
    AuthenticatedCatechistAssignmentsRoute:
      AuthenticatedCatechistAssignmentsRoute,
    AuthenticatedCatechistBranchesRoute: AuthenticatedCatechistBranchesRoute,
    AuthenticatedCatechistCatechistsRoute:
      AuthenticatedCatechistCatechistsRoute,
    AuthenticatedCatechistClassesRoute: AuthenticatedCatechistClassesRoute,
    AuthenticatedCatechistStudentsRoute: AuthenticatedCatechistStudentsRoute,
    AuthenticatedCatechistAssignmentsEditRoute:
      AuthenticatedCatechistAssignmentsEditRoute,
    AuthenticatedCatechistBranchesIdRoute:
      AuthenticatedCatechistBranchesIdRoute,
    AuthenticatedCatechistBranchesCreateRoute:
      AuthenticatedCatechistBranchesCreateRoute,
    AuthenticatedCatechistCatechistsIdRoute:
      AuthenticatedCatechistCatechistsIdRoute,
    AuthenticatedCatechistCatechistsCreateRoute:
      AuthenticatedCatechistCatechistsCreateRoute,
    AuthenticatedCatechistClassesIdRoute: AuthenticatedCatechistClassesIdRoute,
    AuthenticatedCatechistClassesBulkCreateRoute:
      AuthenticatedCatechistClassesBulkCreateRoute,
    AuthenticatedCatechistClassesCreateRoute:
      AuthenticatedCatechistClassesCreateRoute,
    AuthenticatedCatechistStudentsIdRoute:
      AuthenticatedCatechistStudentsIdRoute,
    AuthenticatedCatechistStudentsCreateRoute:
      AuthenticatedCatechistStudentsCreateRoute,
    AuthenticatedCatechistBranchesIdEditRoute:
      AuthenticatedCatechistBranchesIdEditRoute,
    AuthenticatedCatechistCatechistsIdEditRoute:
      AuthenticatedCatechistCatechistsIdEditRoute,
    AuthenticatedCatechistClassesIdEditRoute:
      AuthenticatedCatechistClassesIdEditRoute,
    AuthenticatedCatechistStudentsIdEditRoute:
      AuthenticatedCatechistStudentsIdEditRoute,
    AuthenticatedCatechistClassesIdExamsCreateRoute:
      AuthenticatedCatechistClassesIdExamsCreateRoute,
    AuthenticatedCatechistClassesIdSessionsCreateRoute:
      AuthenticatedCatechistClassesIdSessionsCreateRoute,
  }

const AuthenticatedCatechistRouteWithChildren =
  AuthenticatedCatechistRoute._addFileChildren(
    AuthenticatedCatechistRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCatechistRoute: typeof AuthenticatedCatechistRouteWithChildren
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCatechistRoute: AuthenticatedCatechistRouteWithChildren,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AnotherPageRoute: AnotherPageRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
