/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AnotherPageRouteImport } from './routes/anotherPage'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedBranchesRouteImport } from './routes/_authenticated/branches'
import { Route as AuthenticatedAcademicYearsRouteImport } from './routes/_authenticated/academic-years'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnotherPageRoute = AnotherPageRouteImport.update({
  id: '/anotherPage',
  path: '/anotherPage',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBranchesRoute = AuthenticatedBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAcademicYearsRoute =
  AuthenticatedAcademicYearsRouteImport.update({
    id: '/academic-years',
    path: '/academic-years',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anotherPage': typeof AnotherPageRoute
  '/login': typeof LoginRoute
  '/academic-years': typeof AuthenticatedAcademicYearsRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anotherPage': typeof AnotherPageRoute
  '/login': typeof LoginRoute
  '/academic-years': typeof AuthenticatedAcademicYearsRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/anotherPage': typeof AnotherPageRoute
  '/login': typeof LoginRoute
  '/_authenticated/academic-years': typeof AuthenticatedAcademicYearsRoute
  '/_authenticated/branches': typeof AuthenticatedBranchesRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anotherPage'
    | '/login'
    | '/academic-years'
    | '/branches'
    | '/change-password'
    | '/dashboard'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anotherPage'
    | '/login'
    | '/academic-years'
    | '/branches'
    | '/change-password'
    | '/dashboard'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/anotherPage'
    | '/login'
    | '/_authenticated/academic-years'
    | '/_authenticated/branches'
    | '/_authenticated/change-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AnotherPageRoute: typeof AnotherPageRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anotherPage': {
      id: '/anotherPage'
      path: '/anotherPage'
      fullPath: '/anotherPage'
      preLoaderRoute: typeof AnotherPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/branches': {
      id: '/_authenticated/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedBranchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/academic-years': {
      id: '/_authenticated/academic-years'
      path: '/academic-years'
      fullPath: '/academic-years'
      preLoaderRoute: typeof AuthenticatedAcademicYearsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAcademicYearsRoute: typeof AuthenticatedAcademicYearsRoute
  AuthenticatedBranchesRoute: typeof AuthenticatedBranchesRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAcademicYearsRoute: AuthenticatedAcademicYearsRoute,
  AuthenticatedBranchesRoute: AuthenticatedBranchesRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AnotherPageRoute: AnotherPageRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
